// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MetricMetadataDimensionsDimensionArgs extends com.pulumi.resources.ResourceArgs {

    public static final MetricMetadataDimensionsDimensionArgs Empty = new MetricMetadataDimensionsDimensionArgs();

    /**
     * Display name
     * 
     */
    @Import(name="displayName")
    private @Nullable Output<String> displayName;

    /**
     * @return Display name
     * 
     */
    public Optional<Output<String>> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    @Import(name="key", required=true)
    private Output<String> key;

    public Output<String> key() {
        return this.key;
    }

    private MetricMetadataDimensionsDimensionArgs() {}

    private MetricMetadataDimensionsDimensionArgs(MetricMetadataDimensionsDimensionArgs $) {
        this.displayName = $.displayName;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MetricMetadataDimensionsDimensionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MetricMetadataDimensionsDimensionArgs $;

        public Builder() {
            $ = new MetricMetadataDimensionsDimensionArgs();
        }

        public Builder(MetricMetadataDimensionsDimensionArgs defaults) {
            $ = new MetricMetadataDimensionsDimensionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param displayName Display name
         * 
         * @return builder
         * 
         */
        public Builder displayName(@Nullable Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName Display name
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public MetricMetadataDimensionsDimensionArgs build() {
            $.key = Objects.requireNonNull($.key, "expected parameter 'key' to be non-null");
            return $;
        }
    }

}
