// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs extends com.pulumi.resources.ResourceArgs {

    public static final OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs Empty = new OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs();

    @Import(name="supplementaryIdentifier", required=true)
    private Output<String> supplementaryIdentifier;

    public Output<String> supplementaryIdentifier() {
        return this.supplementaryIdentifier;
    }

    private OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs() {}

    private OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs(OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs $) {
        this.supplementaryIdentifier = $.supplementaryIdentifier;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs $;

        public Builder() {
            $ = new OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs();
        }

        public Builder(OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs defaults) {
            $ = new OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs(Objects.requireNonNull(defaults));
        }

        public Builder supplementaryIdentifier(Output<String> supplementaryIdentifier) {
            $.supplementaryIdentifier = supplementaryIdentifier;
            return this;
        }

        public Builder supplementaryIdentifier(String supplementaryIdentifier) {
            return supplementaryIdentifier(Output.of(supplementaryIdentifier));
        }

        public OwnershipTeamsSupplementaryIdentifiersSupplementaryIdentifierArgs build() {
            $.supplementaryIdentifier = Objects.requireNonNull($.supplementaryIdentifier, "expected parameter 'supplementaryIdentifier' to be non-null");
            return $;
        }
    }

}
