// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs Empty = new RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs();

    @Import(name="context")
    private @Nullable Output<String> context;

    public Optional<Output<String>> context() {
        return Optional.ofNullable(this.context);
    }

    @Import(name="key")
    private @Nullable Output<String> key;

    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    private RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs() {}

    private RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs(RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs $) {
        this.context = $.context;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs $;

        public Builder() {
            $ = new RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs();
        }

        public Builder(RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs defaults) {
            $ = new RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs(Objects.requireNonNull(defaults));
        }

        public Builder context(@Nullable Output<String> context) {
            $.context = context;
            return this;
        }

        public Builder context(String context) {
            return context(Output.of(context));
        }

        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public RequestNamingConditionsConditionComparisonNumberRequestAttributeSourceServiceTagTagKeyArgs build() {
            return $;
        }
    }

}
