version: 2
updates:
  - package-ecosystem: "gomod"
    assignees:
      - "pierskarsenbarg"
    schedule:
      interval: "monthly"
      time: "08:00"
    commit-message:
      prefix: "provider"
      include: "scope"
    directory: "/provider"
    groups:
      modules:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "github.com/pulumi/pulumi/sdk/*"
  - package-ecosystem: "gomod"
    assignees:
      - "pierskarsenbarg"
    directory: "/sdk"
    schedule:
      interval: "monthly"
      time: "08:00"
    commit-message:
      prefix: "sdk"
      include: "scope"
    groups:
      modules:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    assignees:
      - "pierskarsenbarg"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
    commit-message:
      prefix: "gha"
      include: "scope"
    groups:
      modules:
        applies-to: version-updates
        update-types:
          - minor
          - patch
