// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Outputs
{

    [OutputType]
    public sealed class ServiceExternalWebServiceIdContributorsUrlPathServiceIdContributor
    {
        public readonly string ContributionType;
        public readonly Outputs.ServiceExternalWebServiceIdContributorsUrlPathServiceIdContributorTransformations? Transformations;
        public readonly Outputs.ServiceExternalWebServiceIdContributorsUrlPathServiceIdContributorValueOverride? ValueOverride;

        [OutputConstructor]
        private ServiceExternalWebServiceIdContributorsUrlPathServiceIdContributor(
            string contributionType,

            Outputs.ServiceExternalWebServiceIdContributorsUrlPathServiceIdContributorTransformations? transformations,

            Outputs.ServiceExternalWebServiceIdContributorsUrlPathServiceIdContributorValueOverride? valueOverride)
        {
            ContributionType = contributionType;
            Transformations = transformations;
            ValueOverride = valueOverride;
        }
    }
}
