// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace
{
    [DynatraceResourceType("dynatrace:index/automationControllerConnections:AutomationControllerConnections")]
    public partial class AutomationControllerConnections : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A unique and clearly identifiable connection name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// API access token for the Ansible Automation Controller. Please note that this token is not refreshed and can expire.
        /// </summary>
        [Output("token")]
        public Output<string?> Token { get; private set; } = null!;

        /// <summary>
        /// Possible Values: `Api_token`
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// URL of the Ansible Automation Controller API endpoint. For example, https://ansible.yourdomain.com/api/v2/
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a AutomationControllerConnections resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AutomationControllerConnections(string name, AutomationControllerConnectionsArgs args, CustomResourceOptions? options = null)
            : base("dynatrace:index/automationControllerConnections:AutomationControllerConnections", name, args ?? new AutomationControllerConnectionsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AutomationControllerConnections(string name, Input<string> id, AutomationControllerConnectionsState? state = null, CustomResourceOptions? options = null)
            : base("dynatrace:index/automationControllerConnections:AutomationControllerConnections", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
                AdditionalSecretOutputs =
                {
                    "token",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AutomationControllerConnections resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AutomationControllerConnections Get(string name, Input<string> id, AutomationControllerConnectionsState? state = null, CustomResourceOptions? options = null)
        {
            return new AutomationControllerConnections(name, id, state, options);
        }
    }

    public sealed class AutomationControllerConnectionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A unique and clearly identifiable connection name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// API access token for the Ansible Automation Controller. Please note that this token is not refreshed and can expire.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Possible Values: `Api_token`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// URL of the Ansible Automation Controller API endpoint. For example, https://ansible.yourdomain.com/api/v2/
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public AutomationControllerConnectionsArgs()
        {
        }
        public static new AutomationControllerConnectionsArgs Empty => new AutomationControllerConnectionsArgs();
    }

    public sealed class AutomationControllerConnectionsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A unique and clearly identifiable connection name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// API access token for the Ansible Automation Controller. Please note that this token is not refreshed and can expire.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Possible Values: `Api_token`
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// URL of the Ansible Automation Controller API endpoint. For example, https://ansible.yourdomain.com/api/v2/
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public AutomationControllerConnectionsState()
        {
        }
        public static new AutomationControllerConnectionsState Empty => new AutomationControllerConnectionsState();
    }
}
