// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace
{
    [DynatraceResourceType("dynatrace:index/discoveryDefaultRules:DiscoveryDefaultRules")]
    public partial class DiscoveryDefaultRules : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Rule:
        /// </summary>
        [Output("rule")]
        public Output<Outputs.DiscoveryDefaultRulesRule> Rule { get; private set; } = null!;

        /// <summary>
        /// Settings:
        /// </summary>
        [Output("settings")]
        public Output<Outputs.DiscoveryDefaultRulesSettings> Settings { get; private set; } = null!;


        /// <summary>
        /// Create a DiscoveryDefaultRules resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DiscoveryDefaultRules(string name, DiscoveryDefaultRulesArgs args, CustomResourceOptions? options = null)
            : base("dynatrace:index/discoveryDefaultRules:DiscoveryDefaultRules", name, args ?? new DiscoveryDefaultRulesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DiscoveryDefaultRules(string name, Input<string> id, DiscoveryDefaultRulesState? state = null, CustomResourceOptions? options = null)
            : base("dynatrace:index/discoveryDefaultRules:DiscoveryDefaultRules", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DiscoveryDefaultRules resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DiscoveryDefaultRules Get(string name, Input<string> id, DiscoveryDefaultRulesState? state = null, CustomResourceOptions? options = null)
        {
            return new DiscoveryDefaultRules(name, id, state, options);
        }
    }

    public sealed class DiscoveryDefaultRulesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Rule:
        /// </summary>
        [Input("rule", required: true)]
        public Input<Inputs.DiscoveryDefaultRulesRuleArgs> Rule { get; set; } = null!;

        /// <summary>
        /// Settings:
        /// </summary>
        [Input("settings", required: true)]
        public Input<Inputs.DiscoveryDefaultRulesSettingsArgs> Settings { get; set; } = null!;

        public DiscoveryDefaultRulesArgs()
        {
        }
        public static new DiscoveryDefaultRulesArgs Empty => new DiscoveryDefaultRulesArgs();
    }

    public sealed class DiscoveryDefaultRulesState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Rule:
        /// </summary>
        [Input("rule")]
        public Input<Inputs.DiscoveryDefaultRulesRuleGetArgs>? Rule { get; set; }

        /// <summary>
        /// Settings:
        /// </summary>
        [Input("settings")]
        public Input<Inputs.DiscoveryDefaultRulesSettingsGetArgs>? Settings { get; set; }

        public DiscoveryDefaultRulesState()
        {
        }
        public static new DiscoveryDefaultRulesState Empty => new DiscoveryDefaultRulesState();
    }
}
