// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dynatrace.TransactionStartFiltersArgs;
import com.pulumi.dynatrace.Utilities;
import com.pulumi.dynatrace.inputs.TransactionStartFiltersState;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="dynatrace:index/transactionStartFilters:TransactionStartFilters")
public class TransactionStartFilters extends com.pulumi.resources.CustomResource {
    /**
     * You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    @Export(name="cicsTerminalTransactionIds", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> cicsTerminalTransactionIds;

    /**
     * @return You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    public Output<Optional<List<String>>> cicsTerminalTransactionIds() {
        return Codegen.optional(this.cicsTerminalTransactionIds);
    }
    /**
     * You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    @Export(name="cicsTransactionIds", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> cicsTransactionIds;

    /**
     * @return You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    public Output<Optional<List<String>>> cicsTransactionIds() {
        return Codegen.optional(this.cicsTransactionIds);
    }
    /**
     * You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    @Export(name="imsTerminalTransactionIds", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> imsTerminalTransactionIds;

    /**
     * @return You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    public Output<Optional<List<String>>> imsTerminalTransactionIds() {
        return Codegen.optional(this.imsTerminalTransactionIds);
    }
    /**
     * You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    @Export(name="imsTransactionIds", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> imsTransactionIds;

    /**
     * @return You can use * as wildcard. For example use A* to trace all transaction IDs that start with A.
     * 
     */
    public Output<Optional<List<String>>> imsTransactionIds() {
        return Codegen.optional(this.imsTransactionIds);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TransactionStartFilters(String name) {
        this(name, TransactionStartFiltersArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TransactionStartFilters(String name, @Nullable TransactionStartFiltersArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TransactionStartFilters(String name, @Nullable TransactionStartFiltersArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dynatrace:index/transactionStartFilters:TransactionStartFilters", name, args == null ? TransactionStartFiltersArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private TransactionStartFilters(String name, Output<String> id, @Nullable TransactionStartFiltersState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dynatrace:index/transactionStartFilters:TransactionStartFilters", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TransactionStartFilters get(String name, Output<String> id, @Nullable TransactionStartFiltersState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TransactionStartFilters(name, id, state, options);
    }
}
