// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class DashboardDashboardMetadataSharingDetails
    {
        /// <summary>
        /// If `true`, the dashboard is shared via link and authenticated users with the link can view
        /// </summary>
        public readonly bool? LinkShared;
        /// <summary>
        /// If `true`, the dashboard is published to anyone on this environment
        /// </summary>
        public readonly bool? Published;
        /// <summary>
        /// allows for configuring properties that are not explicitly supported by the current version of this provider
        /// </summary>
        public readonly string? Unknowns;

        [OutputConstructor]
        private DashboardDashboardMetadataSharingDetails(
            bool? linkShared,

            bool? published,

            string? unknowns)
        {
            LinkShared = linkShared;
            Published = published;
            Unknowns = unknowns;
        }
    }
}
