// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class DiskSpecificAnomaliesV2DiskLowInodesDetection
    {
        /// <summary>
        /// no documentation available
        /// </summary>
        public readonly Outputs.DiskSpecificAnomaliesV2DiskLowInodesDetectionCustomThresholds? CustomThresholds;
        /// <summary>
        /// Detection mode for low inodes number available
        /// </summary>
        public readonly string? DetectionMode;
        /// <summary>
        /// Detect low inodes number available
        /// </summary>
        public readonly bool Enabled;

        [OutputConstructor]
        private DiskSpecificAnomaliesV2DiskLowInodesDetection(
            Outputs.DiskSpecificAnomaliesV2DiskLowInodesDetectionCustomThresholds? customThresholds,

            string? detectionMode,

            bool enabled)
        {
            CustomThresholds = customThresholds;
            DetectionMode = detectionMode;
            Enabled = enabled;
        }
    }
}
