// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class MobileAppEnablementSessionReplay
    {
        /// <summary>
        /// Percentage of user sessions recorded with Session Replay. For example, if you have 50% for RUM and 50% for Session Replay, it results in 25% of sessions recorded with Session Replay.
        /// </summary>
        public readonly int? CostAndTrafficControl;
        /// <summary>
        /// Before enabling, Dynatrace checks your system against the [prerequisites for Session Replay](https://dt-url.net/t23s0ppi).
        /// </summary>
        public readonly bool? FullSessionReplay;
        /// <summary>
        /// Enable New Session Replay Experience
        /// </summary>
        public readonly bool? FullSessionReplayOnGrail;
        /// <summary>
        /// Capture screen recordings that replay the user actions preceding all detected crashes. Before enabling, Dynatrace checks your system against the [prerequisites for Session Replay](https://dt-url.net/t23s0ppi).
        /// </summary>
        public readonly bool OnCrash;
        /// <summary>
        /// Enable New Session Replay on Crashes Experience
        /// </summary>
        public readonly bool? OnCrashOnGrail;

        [OutputConstructor]
        private MobileAppEnablementSessionReplay(
            int? costAndTrafficControl,

            bool? fullSessionReplay,

            bool? fullSessionReplayOnGrail,

            bool onCrash,

            bool? onCrashOnGrail)
        {
            CostAndTrafficControl = costAndTrafficControl;
            FullSessionReplay = fullSessionReplay;
            FullSessionReplayOnGrail = fullSessionReplayOnGrail;
            OnCrash = onCrash;
            OnCrashOnGrail = onCrashOnGrail;
        }
    }
}
