// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorAzureLogForwarding
    {
        /// <summary>
        /// Field Extraction
        /// </summary>
        public readonly Outputs.OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorAzureLogForwardingFieldExtraction FieldExtraction;
        /// <summary>
        /// no documentation available
        /// </summary>
        public readonly string ForwarderConfigId;

        [OutputConstructor]
        private OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorAzureLogForwarding(
            Outputs.OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorAzureLogForwardingFieldExtraction fieldExtraction,

            string forwarderConfigId)
        {
            FieldExtraction = fieldExtraction;
            ForwarderConfigId = forwarderConfigId;
        }
    }
}
