// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorSamplingAwareCounterMetricDimensions
    {
        public readonly ImmutableArray<Outputs.OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorSamplingAwareCounterMetricDimensionsDimension> Dimensions;

        [OutputConstructor]
        private OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorSamplingAwareCounterMetricDimensions(ImmutableArray<Outputs.OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorSamplingAwareCounterMetricDimensionsDimension> dimensions)
        {
            Dimensions = dimensions;
        }
    }
}
