// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2SystemEventsPipelinesDataExtractionProcessorsProcessorSmartscapeNodeFieldsToExtract
    {
        public readonly ImmutableArray<Outputs.OpenpipelineV2SystemEventsPipelinesDataExtractionProcessorsProcessorSmartscapeNodeFieldsToExtractSmartscapeFieldExtractionEntry> SmartscapeFieldExtractionEntries;

        [OutputConstructor]
        private OpenpipelineV2SystemEventsPipelinesDataExtractionProcessorsProcessorSmartscapeNodeFieldsToExtract(ImmutableArray<Outputs.OpenpipelineV2SystemEventsPipelinesDataExtractionProcessorsProcessorSmartscapeNodeFieldsToExtractSmartscapeFieldExtractionEntry> smartscapeFieldExtractionEntries)
        {
            SmartscapeFieldExtractionEntries = smartscapeFieldExtractionEntries;
        }
    }
}
