// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAddFields
    {
        public readonly ImmutableArray<Outputs.OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAddFieldsField> Fields;

        [OutputConstructor]
        private OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAddFields(ImmutableArray<Outputs.OpenpipelineV2UserEventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAddFieldsField> fields)
        {
            Fields = fields;
        }
    }
}
