// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessor
    {
        /// <summary>
        /// Azure log forwarding processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorAzureLogForwarding? AzureLogForwarding;
        /// <summary>
        /// Bizevent extraction processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorBizevent? Bizevent;
        /// <summary>
        /// Bucket assignment processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorBucketAssignment? BucketAssignment;
        /// <summary>
        /// Cost allocation processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorCostAllocation? CostAllocation;
        /// <summary>
        /// Counter metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorCounterMetric? CounterMetric;
        /// <summary>
        /// Davis event extraction processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorDavis? Davis;
        /// <summary>
        /// no documentation available
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// DQL processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorDql? Dql;
        /// <summary>
        /// This setting is enabled (`True`) or disabled (`False`)
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Fields add processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorFieldsAdd? FieldsAdd;
        /// <summary>
        /// Fields remove processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorFieldsRemove? FieldsRemove;
        /// <summary>
        /// Fields rename processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorFieldsRename? FieldsRename;
        /// <summary>
        /// Histogram metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorHistogramMetric? HistogramMetric;
        /// <summary>
        /// Processor identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// [See our documentation](https://dt-url.net/bp234rv)
        /// </summary>
        public readonly string? Matcher;
        /// <summary>
        /// Product allocation processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorProductAllocation? ProductAllocation;
        /// <summary>
        /// Sample data
        /// </summary>
        public readonly string? SampleData;
        /// <summary>
        /// Sampling-aware counter metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSamplingAwareCounterMetric? SamplingAwareCounterMetric;
        /// <summary>
        /// Sampling aware value metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSamplingAwareValueMetric? SamplingAwareValueMetric;
        /// <summary>
        /// Security context processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSecurityContext? SecurityContext;
        /// <summary>
        /// Security event extraction processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSecurityEvent? SecurityEvent;
        /// <summary>
        /// Technology processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorTechnology? Technology;
        /// <summary>
        /// Processor type. Possible Values: `azureLogForwarding`, `Bizevent`, `bucketAssignment`, `costAllocation`, `counterMetric`, `Davis`, `Dql`, `Drop`, `fieldsAdd`, `fieldsRemove`, `fieldsRename`, `histogramMetric`, `noStorage`, `productAllocation`, `samplingAwareCounterMetric`, `samplingAwareValueMetric`, `securityContext`, `securityEvent`, `Technology`, `valueMetric`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Value metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorValueMetric? ValueMetric;

        [OutputConstructor]
        private OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessor(
            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorAzureLogForwarding? azureLogForwarding,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorBizevent? bizevent,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorBucketAssignment? bucketAssignment,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorCostAllocation? costAllocation,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorCounterMetric? counterMetric,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorDavis? davis,

            string description,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorDql? dql,

            bool enabled,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorFieldsAdd? fieldsAdd,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorFieldsRemove? fieldsRemove,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorFieldsRename? fieldsRename,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorHistogramMetric? histogramMetric,

            string id,

            string? matcher,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorProductAllocation? productAllocation,

            string? sampleData,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSamplingAwareCounterMetric? samplingAwareCounterMetric,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSamplingAwareValueMetric? samplingAwareValueMetric,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSecurityContext? securityContext,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorSecurityEvent? securityEvent,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorTechnology? technology,

            string type,

            Outputs.OpenpipelineV2EventsSdlcIngestsourcesProcessingProcessorsProcessorValueMetric? valueMetric)
        {
            AzureLogForwarding = azureLogForwarding;
            Bizevent = bizevent;
            BucketAssignment = bucketAssignment;
            CostAllocation = costAllocation;
            CounterMetric = counterMetric;
            Davis = davis;
            Description = description;
            Dql = dql;
            Enabled = enabled;
            FieldsAdd = fieldsAdd;
            FieldsRemove = fieldsRemove;
            FieldsRename = fieldsRename;
            HistogramMetric = histogramMetric;
            Id = id;
            Matcher = matcher;
            ProductAllocation = productAllocation;
            SampleData = sampleData;
            SamplingAwareCounterMetric = samplingAwareCounterMetric;
            SamplingAwareValueMetric = samplingAwareValueMetric;
            SecurityContext = securityContext;
            SecurityEvent = securityEvent;
            Technology = technology;
            Type = type;
            ValueMetric = valueMetric;
        }
    }
}
