// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2SecurityEventsDataforwardingProcessingProcessorsProcessorSecurityEvent
    {
        /// <summary>
        /// Field Extraction
        /// </summary>
        public readonly Outputs.OpenpipelineV2SecurityEventsDataforwardingProcessingProcessorsProcessorSecurityEventFieldExtraction FieldExtraction;

        [OutputConstructor]
        private OpenpipelineV2SecurityEventsDataforwardingProcessingProcessorsProcessorSecurityEvent(Outputs.OpenpipelineV2SecurityEventsDataforwardingProcessingProcessorsProcessorSecurityEventFieldExtraction fieldExtraction)
        {
            FieldExtraction = fieldExtraction;
        }
    }
}
