// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2EventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAdd
    {
        /// <summary>
        /// Fields to Add
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAddFields Fields;

        [OutputConstructor]
        private OpenpipelineV2EventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAdd(Outputs.OpenpipelineV2EventsPipelinesSmartscapeNodeExtractionProcessorsProcessorFieldsAddFields fields)
        {
            Fields = fields;
        }
    }
}
