// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2EventsDataforwardingProcessingProcessorsProcessorSamplingAwareHistogramMetricDimensions
    {
        public readonly ImmutableArray<Outputs.OpenpipelineV2EventsDataforwardingProcessingProcessorsProcessorSamplingAwareHistogramMetricDimensionsFieldExtractionEntry> FieldExtractionEntries;

        [OutputConstructor]
        private OpenpipelineV2EventsDataforwardingProcessingProcessorsProcessorSamplingAwareHistogramMetricDimensions(ImmutableArray<Outputs.OpenpipelineV2EventsDataforwardingProcessingProcessorsProcessorSamplingAwareHistogramMetricDimensionsFieldExtractionEntry> fieldExtractionEntries)
        {
            FieldExtractionEntries = fieldExtractionEntries;
        }
    }
}
