// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizevent
    {
        /// <summary>
        /// Event provider
        /// </summary>
        public readonly Outputs.OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizeventEventProvider EventProvider;
        /// <summary>
        /// Event type
        /// </summary>
        public readonly Outputs.OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizeventEventType? EventType;
        /// <summary>
        /// Field extraction
        /// </summary>
        public readonly Outputs.OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizeventFieldExtraction FieldExtraction;

        [OutputConstructor]
        private OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizevent(
            Outputs.OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizeventEventProvider eventProvider,

            Outputs.OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizeventEventType? eventType,

            Outputs.OpenpipelineV2DavisProblemsPipelinesDataExtractionProcessorsProcessorBizeventFieldExtraction fieldExtraction)
        {
            EventProvider = eventProvider;
            EventType = eventType;
            FieldExtraction = fieldExtraction;
        }
    }
}
