// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2EventsSecurityPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtraction
    {
        /// <summary>
        /// Fields
        /// </summary>
        public readonly ImmutableArray<string> Excludes;
        /// <summary>
        /// Fields
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSecurityPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionInclude? Include;
        /// <summary>
        /// Fields Extraction type. Possible Values: `Exclude`, `Include`, `includeAll`
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private OpenpipelineV2EventsSecurityPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtraction(
            ImmutableArray<string> excludes,

            Outputs.OpenpipelineV2EventsSecurityPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionInclude? include,

            string type)
        {
            Excludes = excludes;
            Include = include;
            Type = type;
        }
    }
}
