// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2UsersessionsPipelinesSmartscapeEdgeExtractionProcessorsProcessorBizeventFieldExtractionInclude
    {
        public readonly ImmutableArray<Outputs.OpenpipelineV2UsersessionsPipelinesSmartscapeEdgeExtractionProcessorsProcessorBizeventFieldExtractionIncludeDimension> Dimensions;

        [OutputConstructor]
        private OpenpipelineV2UsersessionsPipelinesSmartscapeEdgeExtractionProcessorsProcessorBizeventFieldExtractionInclude(ImmutableArray<Outputs.OpenpipelineV2UsersessionsPipelinesSmartscapeEdgeExtractionProcessorsProcessorBizeventFieldExtractionIncludeDimension> dimensions)
        {
            Dimensions = dimensions;
        }
    }
}
