// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessor
    {
        /// <summary>
        /// Azure log forwarding processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorAzureLogForwarding? AzureLogForwarding;
        /// <summary>
        /// Bizevent extraction processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorBizevent? Bizevent;
        /// <summary>
        /// Bucket assignment processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorBucketAssignment? BucketAssignment;
        /// <summary>
        /// Cost allocation processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorCostAllocation? CostAllocation;
        /// <summary>
        /// Counter metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorCounterMetric? CounterMetric;
        /// <summary>
        /// Davis event extraction processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorDavis? Davis;
        /// <summary>
        /// no documentation available
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// DQL processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorDql? Dql;
        /// <summary>
        /// This setting is enabled (`True`) or disabled (`False`)
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Fields add processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorFieldsAdd? FieldsAdd;
        /// <summary>
        /// Fields remove processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorFieldsRemove? FieldsRemove;
        /// <summary>
        /// Fields rename processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorFieldsRename? FieldsRename;
        /// <summary>
        /// Histogram metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorHistogramMetric? HistogramMetric;
        /// <summary>
        /// Processor identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// [See our documentation](https://dt-url.net/bp234rv)
        /// </summary>
        public readonly string? Matcher;
        /// <summary>
        /// Product allocation processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorProductAllocation? ProductAllocation;
        /// <summary>
        /// Sample data
        /// </summary>
        public readonly string? SampleData;
        /// <summary>
        /// Sampling-aware counter metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSamplingAwareCounterMetric? SamplingAwareCounterMetric;
        /// <summary>
        /// Sampling aware value metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSamplingAwareValueMetric? SamplingAwareValueMetric;
        /// <summary>
        /// Security context processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSecurityContext? SecurityContext;
        /// <summary>
        /// Security event extraction processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSecurityEvent? SecurityEvent;
        /// <summary>
        /// Technology processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorTechnology? Technology;
        /// <summary>
        /// Processor type. Possible Values: `azureLogForwarding`, `Bizevent`, `bucketAssignment`, `costAllocation`, `counterMetric`, `Davis`, `Dql`, `Drop`, `fieldsAdd`, `fieldsRemove`, `fieldsRename`, `histogramMetric`, `noStorage`, `productAllocation`, `samplingAwareCounterMetric`, `samplingAwareValueMetric`, `securityContext`, `securityEvent`, `Technology`, `valueMetric`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Value metric processor attributes
        /// </summary>
        public readonly Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorValueMetric? ValueMetric;

        [OutputConstructor]
        private OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessor(
            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorAzureLogForwarding? azureLogForwarding,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorBizevent? bizevent,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorBucketAssignment? bucketAssignment,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorCostAllocation? costAllocation,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorCounterMetric? counterMetric,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorDavis? davis,

            string description,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorDql? dql,

            bool enabled,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorFieldsAdd? fieldsAdd,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorFieldsRemove? fieldsRemove,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorFieldsRename? fieldsRename,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorHistogramMetric? histogramMetric,

            string id,

            string? matcher,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorProductAllocation? productAllocation,

            string? sampleData,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSamplingAwareCounterMetric? samplingAwareCounterMetric,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSamplingAwareValueMetric? samplingAwareValueMetric,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSecurityContext? securityContext,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorSecurityEvent? securityEvent,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorTechnology? technology,

            string type,

            Outputs.OpenpipelineV2BizeventsPipelinesDataExtractionProcessorsProcessorValueMetric? valueMetric)
        {
            AzureLogForwarding = azureLogForwarding;
            Bizevent = bizevent;
            BucketAssignment = bucketAssignment;
            CostAllocation = costAllocation;
            CounterMetric = counterMetric;
            Davis = davis;
            Description = description;
            Dql = dql;
            Enabled = enabled;
            FieldsAdd = fieldsAdd;
            FieldsRemove = fieldsRemove;
            FieldsRename = fieldsRename;
            HistogramMetric = histogramMetric;
            Id = id;
            Matcher = matcher;
            ProductAllocation = productAllocation;
            SampleData = sampleData;
            SamplingAwareCounterMetric = samplingAwareCounterMetric;
            SamplingAwareValueMetric = samplingAwareValueMetric;
            SecurityContext = securityContext;
            SecurityEvent = securityEvent;
            Technology = technology;
            Type = type;
            ValueMetric = valueMetric;
        }
    }
}
