// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2BizeventsPipelinesProcessingProcessors
    {
        public readonly ImmutableArray<Outputs.OpenpipelineV2BizeventsPipelinesProcessingProcessorsProcessor> Processors;

        [OutputConstructor]
        private OpenpipelineV2BizeventsPipelinesProcessingProcessors(ImmutableArray<Outputs.OpenpipelineV2BizeventsPipelinesProcessingProcessorsProcessor> processors)
        {
            Processors = processors;
        }
    }
}
