// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2DavisEventsPipelinesStorageProcessorsProcessorSecurityEvent
    {
        /// <summary>
        /// Field Extraction
        /// </summary>
        public readonly Outputs.OpenpipelineV2DavisEventsPipelinesStorageProcessorsProcessorSecurityEventFieldExtraction FieldExtraction;

        [OutputConstructor]
        private OpenpipelineV2DavisEventsPipelinesStorageProcessorsProcessorSecurityEvent(Outputs.OpenpipelineV2DavisEventsPipelinesStorageProcessorsProcessorSecurityEventFieldExtraction fieldExtraction)
        {
            FieldExtraction = fieldExtraction;
        }
    }
}
