// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2EventsSdlcDataforwardingProcessingProcessorsProcessorDavis
    {
        /// <summary>
        /// No documentation available
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcDataforwardingProcessingProcessorsProcessorDavisProperties Properties;

        [OutputConstructor]
        private OpenpipelineV2EventsSdlcDataforwardingProcessingProcessorsProcessorDavis(Outputs.OpenpipelineV2EventsSdlcDataforwardingProcessingProcessorsProcessorDavisProperties properties)
        {
            Properties = properties;
        }
    }
}
