// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class OpenpipelineV2EventsSdlcPipelinesSmartscapeEdgeExtractionProcessorsProcessorCounterMetric
    {
        /// <summary>
        /// List of dimensions
        /// </summary>
        public readonly Outputs.OpenpipelineV2EventsSdlcPipelinesSmartscapeEdgeExtractionProcessorsProcessorCounterMetricDimensions? Dimensions;
        /// <summary>
        /// Metric key
        /// </summary>
        public readonly string MetricKey;

        [OutputConstructor]
        private OpenpipelineV2EventsSdlcPipelinesSmartscapeEdgeExtractionProcessorsProcessorCounterMetric(
            Outputs.OpenpipelineV2EventsSdlcPipelinesSmartscapeEdgeExtractionProcessorsProcessorCounterMetricDimensions? dimensions,

            string metricKey)
        {
            Dimensions = dimensions;
            MetricKey = metricKey;
        }
    }
}
