// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class ServiceFullWebRequestIdContributorsContextRoot
    {
        /// <summary>
        /// When enabled, the context root contributes to the Service Id.
        /// </summary>
        public readonly bool EnableIdContributor;
        /// <summary>
        /// Choose how to transform the context root value before it contributes to the Service Id. Note that all of the Transformations are always applied. Transformations are applied in the order they are specified, and the output of the previous transformation is the input for the next one.
        /// </summary>
        public readonly Outputs.ServiceFullWebRequestIdContributorsContextRootServiceIdContributor? ServiceIdContributor;

        [OutputConstructor]
        private ServiceFullWebRequestIdContributorsContextRoot(
            bool enableIdContributor,

            Outputs.ServiceFullWebRequestIdContributorsContextRootServiceIdContributor? serviceIdContributor)
        {
            EnableIdContributor = enableIdContributor;
            ServiceIdContributor = serviceIdContributor;
        }
    }
}
