// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Outputs
{

    [OutputType]
    public sealed class SettingsPermissionsGroupsGroup
    {
        /// <summary>
        /// Valid values: `Read`, `Write`
        /// </summary>
        public readonly string Access;
        /// <summary>
        /// The UUID of the group, conveniently retrieved via the `Id` attribute provided by the data source `dynatrace*iam*group
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private SettingsPermissionsGroupsGroup(
            string access,

            string id)
        {
            Access = access;
            Id = id;
        }
    }
}
