// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.PulumiPackage.Dynatrace
{
    public static class GetRemoteEnvironments
    {
        /// <summary>
        /// The remote environments data source allows retrieval of all remote environments.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Dynatrace = Pulumi.Dynatrace;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Dynatrace.GetRemoteEnvironments.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["remoteEnvironments"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetRemoteEnvironmentsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRemoteEnvironmentsResult>("dynatrace:index/getRemoteEnvironments:getRemoteEnvironments", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// The remote environments data source allows retrieval of all remote environments.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Dynatrace = Pulumi.Dynatrace;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Dynatrace.GetRemoteEnvironments.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["remoteEnvironments"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetRemoteEnvironmentsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRemoteEnvironmentsResult>("dynatrace:index/getRemoteEnvironments:getRemoteEnvironments", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetRemoteEnvironmentsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetRemoteEnvironmentsRemoteEnvironmentResult> RemoteEnvironments;

        [OutputConstructor]
        private GetRemoteEnvironmentsResult(
            string id,

            ImmutableArray<Outputs.GetRemoteEnvironmentsRemoteEnvironmentResult> remoteEnvironments)
        {
            Id = id;
            RemoteEnvironments = remoteEnvironments;
        }
    }
}
