// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dynatrace

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-dynatrace/sdk/go/dynatrace/internal"
)

var _ = internal.GetEnvOrDefault

type GetDocumentsValue struct {
	// The unique identifier of the document.
	Id string `pulumi:"id"`
	// The name of the document.
	Name string `pulumi:"name"`
	// The owner of the document. This could be a user or a group that has ownership rights over the document.
	Owner string `pulumi:"owner"`
	// The type of the document. This could be a specific format or category the document belongs to.
	Type string `pulumi:"type"`
}

// GetDocumentsValueInput is an input type that accepts GetDocumentsValueArgs and GetDocumentsValueOutput values.
// You can construct a concrete instance of `GetDocumentsValueInput` via:
//
//	GetDocumentsValueArgs{...}
type GetDocumentsValueInput interface {
	pulumi.Input

	ToGetDocumentsValueOutput() GetDocumentsValueOutput
	ToGetDocumentsValueOutputWithContext(context.Context) GetDocumentsValueOutput
}

type GetDocumentsValueArgs struct {
	// The unique identifier of the document.
	Id pulumi.StringInput `pulumi:"id"`
	// The name of the document.
	Name pulumi.StringInput `pulumi:"name"`
	// The owner of the document. This could be a user or a group that has ownership rights over the document.
	Owner pulumi.StringInput `pulumi:"owner"`
	// The type of the document. This could be a specific format or category the document belongs to.
	Type pulumi.StringInput `pulumi:"type"`
}

func (GetDocumentsValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDocumentsValue)(nil)).Elem()
}

func (i GetDocumentsValueArgs) ToGetDocumentsValueOutput() GetDocumentsValueOutput {
	return i.ToGetDocumentsValueOutputWithContext(context.Background())
}

func (i GetDocumentsValueArgs) ToGetDocumentsValueOutputWithContext(ctx context.Context) GetDocumentsValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDocumentsValueOutput)
}

// GetDocumentsValueArrayInput is an input type that accepts GetDocumentsValueArray and GetDocumentsValueArrayOutput values.
// You can construct a concrete instance of `GetDocumentsValueArrayInput` via:
//
//	GetDocumentsValueArray{ GetDocumentsValueArgs{...} }
type GetDocumentsValueArrayInput interface {
	pulumi.Input

	ToGetDocumentsValueArrayOutput() GetDocumentsValueArrayOutput
	ToGetDocumentsValueArrayOutputWithContext(context.Context) GetDocumentsValueArrayOutput
}

type GetDocumentsValueArray []GetDocumentsValueInput

func (GetDocumentsValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDocumentsValue)(nil)).Elem()
}

func (i GetDocumentsValueArray) ToGetDocumentsValueArrayOutput() GetDocumentsValueArrayOutput {
	return i.ToGetDocumentsValueArrayOutputWithContext(context.Background())
}

func (i GetDocumentsValueArray) ToGetDocumentsValueArrayOutputWithContext(ctx context.Context) GetDocumentsValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDocumentsValueArrayOutput)
}

type GetDocumentsValueOutput struct{ *pulumi.OutputState }

func (GetDocumentsValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDocumentsValue)(nil)).Elem()
}

func (o GetDocumentsValueOutput) ToGetDocumentsValueOutput() GetDocumentsValueOutput {
	return o
}

func (o GetDocumentsValueOutput) ToGetDocumentsValueOutputWithContext(ctx context.Context) GetDocumentsValueOutput {
	return o
}

// The unique identifier of the document.
func (o GetDocumentsValueOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the document.
func (o GetDocumentsValueOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Name }).(pulumi.StringOutput)
}

// The owner of the document. This could be a user or a group that has ownership rights over the document.
func (o GetDocumentsValueOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Owner }).(pulumi.StringOutput)
}

// The type of the document. This could be a specific format or category the document belongs to.
func (o GetDocumentsValueOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetDocumentsValue) string { return v.Type }).(pulumi.StringOutput)
}

type GetDocumentsValueArrayOutput struct{ *pulumi.OutputState }

func (GetDocumentsValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDocumentsValue)(nil)).Elem()
}

func (o GetDocumentsValueArrayOutput) ToGetDocumentsValueArrayOutput() GetDocumentsValueArrayOutput {
	return o
}

func (o GetDocumentsValueArrayOutput) ToGetDocumentsValueArrayOutputWithContext(ctx context.Context) GetDocumentsValueArrayOutput {
	return o
}

func (o GetDocumentsValueArrayOutput) Index(i pulumi.IntInput) GetDocumentsValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDocumentsValue {
		return vs[0].([]GetDocumentsValue)[vs[1].(int)]
	}).(GetDocumentsValueOutput)
}

type GetEntitiesEntity struct {
	// The name of the entity, displayed in the UI.
	DisplayName *string `pulumi:"displayName"`
	// The ID of the entity.
	EntityId *string `pulumi:"entityId"`
	// The timestamp at which the entity was last seen, in UTC milliseconds.
	LastSeenTms *int `pulumi:"lastSeenTms"`
	// Properties defining the entity.
	Properties map[string]string `pulumi:"properties"`
	// A set of tags assigned to the entity.
	Tags []GetEntitiesEntityTag `pulumi:"tags"`
	// The type of the entity.
	Type *string `pulumi:"type"`
}

// GetEntitiesEntityInput is an input type that accepts GetEntitiesEntityArgs and GetEntitiesEntityOutput values.
// You can construct a concrete instance of `GetEntitiesEntityInput` via:
//
//	GetEntitiesEntityArgs{...}
type GetEntitiesEntityInput interface {
	pulumi.Input

	ToGetEntitiesEntityOutput() GetEntitiesEntityOutput
	ToGetEntitiesEntityOutputWithContext(context.Context) GetEntitiesEntityOutput
}

type GetEntitiesEntityArgs struct {
	// The name of the entity, displayed in the UI.
	DisplayName pulumi.StringPtrInput `pulumi:"displayName"`
	// The ID of the entity.
	EntityId pulumi.StringPtrInput `pulumi:"entityId"`
	// The timestamp at which the entity was last seen, in UTC milliseconds.
	LastSeenTms pulumi.IntPtrInput `pulumi:"lastSeenTms"`
	// Properties defining the entity.
	Properties pulumi.StringMapInput `pulumi:"properties"`
	// A set of tags assigned to the entity.
	Tags GetEntitiesEntityTagArrayInput `pulumi:"tags"`
	// The type of the entity.
	Type pulumi.StringPtrInput `pulumi:"type"`
}

func (GetEntitiesEntityArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntity)(nil)).Elem()
}

func (i GetEntitiesEntityArgs) ToGetEntitiesEntityOutput() GetEntitiesEntityOutput {
	return i.ToGetEntitiesEntityOutputWithContext(context.Background())
}

func (i GetEntitiesEntityArgs) ToGetEntitiesEntityOutputWithContext(ctx context.Context) GetEntitiesEntityOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityOutput)
}

// GetEntitiesEntityArrayInput is an input type that accepts GetEntitiesEntityArray and GetEntitiesEntityArrayOutput values.
// You can construct a concrete instance of `GetEntitiesEntityArrayInput` via:
//
//	GetEntitiesEntityArray{ GetEntitiesEntityArgs{...} }
type GetEntitiesEntityArrayInput interface {
	pulumi.Input

	ToGetEntitiesEntityArrayOutput() GetEntitiesEntityArrayOutput
	ToGetEntitiesEntityArrayOutputWithContext(context.Context) GetEntitiesEntityArrayOutput
}

type GetEntitiesEntityArray []GetEntitiesEntityInput

func (GetEntitiesEntityArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntity)(nil)).Elem()
}

func (i GetEntitiesEntityArray) ToGetEntitiesEntityArrayOutput() GetEntitiesEntityArrayOutput {
	return i.ToGetEntitiesEntityArrayOutputWithContext(context.Background())
}

func (i GetEntitiesEntityArray) ToGetEntitiesEntityArrayOutputWithContext(ctx context.Context) GetEntitiesEntityArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityArrayOutput)
}

type GetEntitiesEntityOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntity)(nil)).Elem()
}

func (o GetEntitiesEntityOutput) ToGetEntitiesEntityOutput() GetEntitiesEntityOutput {
	return o
}

func (o GetEntitiesEntityOutput) ToGetEntitiesEntityOutputWithContext(ctx context.Context) GetEntitiesEntityOutput {
	return o
}

// The name of the entity, displayed in the UI.
func (o GetEntitiesEntityOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *string { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// The ID of the entity.
func (o GetEntitiesEntityOutput) EntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *string { return v.EntityId }).(pulumi.StringPtrOutput)
}

// The timestamp at which the entity was last seen, in UTC milliseconds.
func (o GetEntitiesEntityOutput) LastSeenTms() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *int { return v.LastSeenTms }).(pulumi.IntPtrOutput)
}

// Properties defining the entity.
func (o GetEntitiesEntityOutput) Properties() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetEntitiesEntity) map[string]string { return v.Properties }).(pulumi.StringMapOutput)
}

// A set of tags assigned to the entity.
func (o GetEntitiesEntityOutput) Tags() GetEntitiesEntityTagArrayOutput {
	return o.ApplyT(func(v GetEntitiesEntity) []GetEntitiesEntityTag { return v.Tags }).(GetEntitiesEntityTagArrayOutput)
}

// The type of the entity.
func (o GetEntitiesEntityOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntity) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type GetEntitiesEntityArrayOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntity)(nil)).Elem()
}

func (o GetEntitiesEntityArrayOutput) ToGetEntitiesEntityArrayOutput() GetEntitiesEntityArrayOutput {
	return o
}

func (o GetEntitiesEntityArrayOutput) ToGetEntitiesEntityArrayOutputWithContext(ctx context.Context) GetEntitiesEntityArrayOutput {
	return o
}

func (o GetEntitiesEntityArrayOutput) Index(i pulumi.IntInput) GetEntitiesEntityOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEntitiesEntity {
		return vs[0].([]GetEntitiesEntity)[vs[1].(int)]
	}).(GetEntitiesEntityOutput)
}

type GetEntitiesEntityTag struct {
	// A tag assigned to the entity
	Tags []GetEntitiesEntityTagTag `pulumi:"tags"`
}

// GetEntitiesEntityTagInput is an input type that accepts GetEntitiesEntityTagArgs and GetEntitiesEntityTagOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagInput` via:
//
//	GetEntitiesEntityTagArgs{...}
type GetEntitiesEntityTagInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagOutput() GetEntitiesEntityTagOutput
	ToGetEntitiesEntityTagOutputWithContext(context.Context) GetEntitiesEntityTagOutput
}

type GetEntitiesEntityTagArgs struct {
	// A tag assigned to the entity
	Tags GetEntitiesEntityTagTagArrayInput `pulumi:"tags"`
}

func (GetEntitiesEntityTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagArgs) ToGetEntitiesEntityTagOutput() GetEntitiesEntityTagOutput {
	return i.ToGetEntitiesEntityTagOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagArgs) ToGetEntitiesEntityTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagOutput)
}

// GetEntitiesEntityTagArrayInput is an input type that accepts GetEntitiesEntityTagArray and GetEntitiesEntityTagArrayOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagArrayInput` via:
//
//	GetEntitiesEntityTagArray{ GetEntitiesEntityTagArgs{...} }
type GetEntitiesEntityTagArrayInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagArrayOutput() GetEntitiesEntityTagArrayOutput
	ToGetEntitiesEntityTagArrayOutputWithContext(context.Context) GetEntitiesEntityTagArrayOutput
}

type GetEntitiesEntityTagArray []GetEntitiesEntityTagInput

func (GetEntitiesEntityTagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagArray) ToGetEntitiesEntityTagArrayOutput() GetEntitiesEntityTagArrayOutput {
	return i.ToGetEntitiesEntityTagArrayOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagArray) ToGetEntitiesEntityTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagArrayOutput)
}

type GetEntitiesEntityTagOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagOutput) ToGetEntitiesEntityTagOutput() GetEntitiesEntityTagOutput {
	return o
}

func (o GetEntitiesEntityTagOutput) ToGetEntitiesEntityTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagOutput {
	return o
}

// A tag assigned to the entity
func (o GetEntitiesEntityTagOutput) Tags() GetEntitiesEntityTagTagArrayOutput {
	return o.ApplyT(func(v GetEntitiesEntityTag) []GetEntitiesEntityTagTag { return v.Tags }).(GetEntitiesEntityTagTagArrayOutput)
}

type GetEntitiesEntityTagArrayOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagArrayOutput) ToGetEntitiesEntityTagArrayOutput() GetEntitiesEntityTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagArrayOutput) ToGetEntitiesEntityTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagArrayOutput) Index(i pulumi.IntInput) GetEntitiesEntityTagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEntitiesEntityTag {
		return vs[0].([]GetEntitiesEntityTag)[vs[1].(int)]
	}).(GetEntitiesEntityTagOutput)
}

type GetEntitiesEntityTagTag struct {
	// The origin of the tag, such as AWS or Cloud Foundry. Custom tags use the `CONTEXTLESS` value
	Context string `pulumi:"context"`
	// The key of the tag. Custom tags have the tag value here
	Key string `pulumi:"key"`
	// The string representation of the tag
	StringRepresentation *string `pulumi:"stringRepresentation"`
	// The value of the tag. Not applicable to custom tags
	Value *string `pulumi:"value"`
}

// GetEntitiesEntityTagTagInput is an input type that accepts GetEntitiesEntityTagTagArgs and GetEntitiesEntityTagTagOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagTagInput` via:
//
//	GetEntitiesEntityTagTagArgs{...}
type GetEntitiesEntityTagTagInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagTagOutput() GetEntitiesEntityTagTagOutput
	ToGetEntitiesEntityTagTagOutputWithContext(context.Context) GetEntitiesEntityTagTagOutput
}

type GetEntitiesEntityTagTagArgs struct {
	// The origin of the tag, such as AWS or Cloud Foundry. Custom tags use the `CONTEXTLESS` value
	Context pulumi.StringInput `pulumi:"context"`
	// The key of the tag. Custom tags have the tag value here
	Key pulumi.StringInput `pulumi:"key"`
	// The string representation of the tag
	StringRepresentation pulumi.StringPtrInput `pulumi:"stringRepresentation"`
	// The value of the tag. Not applicable to custom tags
	Value pulumi.StringPtrInput `pulumi:"value"`
}

func (GetEntitiesEntityTagTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTagTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagTagArgs) ToGetEntitiesEntityTagTagOutput() GetEntitiesEntityTagTagOutput {
	return i.ToGetEntitiesEntityTagTagOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagTagArgs) ToGetEntitiesEntityTagTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagTagOutput)
}

// GetEntitiesEntityTagTagArrayInput is an input type that accepts GetEntitiesEntityTagTagArray and GetEntitiesEntityTagTagArrayOutput values.
// You can construct a concrete instance of `GetEntitiesEntityTagTagArrayInput` via:
//
//	GetEntitiesEntityTagTagArray{ GetEntitiesEntityTagTagArgs{...} }
type GetEntitiesEntityTagTagArrayInput interface {
	pulumi.Input

	ToGetEntitiesEntityTagTagArrayOutput() GetEntitiesEntityTagTagArrayOutput
	ToGetEntitiesEntityTagTagArrayOutputWithContext(context.Context) GetEntitiesEntityTagTagArrayOutput
}

type GetEntitiesEntityTagTagArray []GetEntitiesEntityTagTagInput

func (GetEntitiesEntityTagTagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTagTag)(nil)).Elem()
}

func (i GetEntitiesEntityTagTagArray) ToGetEntitiesEntityTagTagArrayOutput() GetEntitiesEntityTagTagArrayOutput {
	return i.ToGetEntitiesEntityTagTagArrayOutputWithContext(context.Background())
}

func (i GetEntitiesEntityTagTagArray) ToGetEntitiesEntityTagTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetEntitiesEntityTagTagArrayOutput)
}

type GetEntitiesEntityTagTagOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesEntityTagTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagTagOutput) ToGetEntitiesEntityTagTagOutput() GetEntitiesEntityTagTagOutput {
	return o
}

func (o GetEntitiesEntityTagTagOutput) ToGetEntitiesEntityTagTagOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagOutput {
	return o
}

// The origin of the tag, such as AWS or Cloud Foundry. Custom tags use the `CONTEXTLESS` value
func (o GetEntitiesEntityTagTagOutput) Context() pulumi.StringOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) string { return v.Context }).(pulumi.StringOutput)
}

// The key of the tag. Custom tags have the tag value here
func (o GetEntitiesEntityTagTagOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) string { return v.Key }).(pulumi.StringOutput)
}

// The string representation of the tag
func (o GetEntitiesEntityTagTagOutput) StringRepresentation() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) *string { return v.StringRepresentation }).(pulumi.StringPtrOutput)
}

// The value of the tag. Not applicable to custom tags
func (o GetEntitiesEntityTagTagOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEntitiesEntityTagTag) *string { return v.Value }).(pulumi.StringPtrOutput)
}

type GetEntitiesEntityTagTagArrayOutput struct{ *pulumi.OutputState }

func (GetEntitiesEntityTagTagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetEntitiesEntityTagTag)(nil)).Elem()
}

func (o GetEntitiesEntityTagTagArrayOutput) ToGetEntitiesEntityTagTagArrayOutput() GetEntitiesEntityTagTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagTagArrayOutput) ToGetEntitiesEntityTagTagArrayOutputWithContext(ctx context.Context) GetEntitiesEntityTagTagArrayOutput {
	return o
}

func (o GetEntitiesEntityTagTagArrayOutput) Index(i pulumi.IntInput) GetEntitiesEntityTagTagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetEntitiesEntityTagTag {
		return vs[0].([]GetEntitiesEntityTagTag)[vs[1].(int)]
	}).(GetEntitiesEntityTagTagOutput)
}

type GetGenericSettingsValue struct {
	LocalStorage string `pulumi:"localStorage"`
	Schema       string `pulumi:"schema"`
	Scope        string `pulumi:"scope"`
	Value        string `pulumi:"value"`
}

// GetGenericSettingsValueInput is an input type that accepts GetGenericSettingsValueArgs and GetGenericSettingsValueOutput values.
// You can construct a concrete instance of `GetGenericSettingsValueInput` via:
//
//	GetGenericSettingsValueArgs{...}
type GetGenericSettingsValueInput interface {
	pulumi.Input

	ToGetGenericSettingsValueOutput() GetGenericSettingsValueOutput
	ToGetGenericSettingsValueOutputWithContext(context.Context) GetGenericSettingsValueOutput
}

type GetGenericSettingsValueArgs struct {
	LocalStorage pulumi.StringInput `pulumi:"localStorage"`
	Schema       pulumi.StringInput `pulumi:"schema"`
	Scope        pulumi.StringInput `pulumi:"scope"`
	Value        pulumi.StringInput `pulumi:"value"`
}

func (GetGenericSettingsValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGenericSettingsValue)(nil)).Elem()
}

func (i GetGenericSettingsValueArgs) ToGetGenericSettingsValueOutput() GetGenericSettingsValueOutput {
	return i.ToGetGenericSettingsValueOutputWithContext(context.Background())
}

func (i GetGenericSettingsValueArgs) ToGetGenericSettingsValueOutputWithContext(ctx context.Context) GetGenericSettingsValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGenericSettingsValueOutput)
}

// GetGenericSettingsValueArrayInput is an input type that accepts GetGenericSettingsValueArray and GetGenericSettingsValueArrayOutput values.
// You can construct a concrete instance of `GetGenericSettingsValueArrayInput` via:
//
//	GetGenericSettingsValueArray{ GetGenericSettingsValueArgs{...} }
type GetGenericSettingsValueArrayInput interface {
	pulumi.Input

	ToGetGenericSettingsValueArrayOutput() GetGenericSettingsValueArrayOutput
	ToGetGenericSettingsValueArrayOutputWithContext(context.Context) GetGenericSettingsValueArrayOutput
}

type GetGenericSettingsValueArray []GetGenericSettingsValueInput

func (GetGenericSettingsValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGenericSettingsValue)(nil)).Elem()
}

func (i GetGenericSettingsValueArray) ToGetGenericSettingsValueArrayOutput() GetGenericSettingsValueArrayOutput {
	return i.ToGetGenericSettingsValueArrayOutputWithContext(context.Background())
}

func (i GetGenericSettingsValueArray) ToGetGenericSettingsValueArrayOutputWithContext(ctx context.Context) GetGenericSettingsValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGenericSettingsValueArrayOutput)
}

type GetGenericSettingsValueOutput struct{ *pulumi.OutputState }

func (GetGenericSettingsValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGenericSettingsValue)(nil)).Elem()
}

func (o GetGenericSettingsValueOutput) ToGetGenericSettingsValueOutput() GetGenericSettingsValueOutput {
	return o
}

func (o GetGenericSettingsValueOutput) ToGetGenericSettingsValueOutputWithContext(ctx context.Context) GetGenericSettingsValueOutput {
	return o
}

func (o GetGenericSettingsValueOutput) LocalStorage() pulumi.StringOutput {
	return o.ApplyT(func(v GetGenericSettingsValue) string { return v.LocalStorage }).(pulumi.StringOutput)
}

func (o GetGenericSettingsValueOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v GetGenericSettingsValue) string { return v.Schema }).(pulumi.StringOutput)
}

func (o GetGenericSettingsValueOutput) Scope() pulumi.StringOutput {
	return o.ApplyT(func(v GetGenericSettingsValue) string { return v.Scope }).(pulumi.StringOutput)
}

func (o GetGenericSettingsValueOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v GetGenericSettingsValue) string { return v.Value }).(pulumi.StringOutput)
}

type GetGenericSettingsValueArrayOutput struct{ *pulumi.OutputState }

func (GetGenericSettingsValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGenericSettingsValue)(nil)).Elem()
}

func (o GetGenericSettingsValueArrayOutput) ToGetGenericSettingsValueArrayOutput() GetGenericSettingsValueArrayOutput {
	return o
}

func (o GetGenericSettingsValueArrayOutput) ToGetGenericSettingsValueArrayOutputWithContext(ctx context.Context) GetGenericSettingsValueArrayOutput {
	return o
}

func (o GetGenericSettingsValueArrayOutput) Index(i pulumi.IntInput) GetGenericSettingsValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetGenericSettingsValue {
		return vs[0].([]GetGenericSettingsValue)[vs[1].(int)]
	}).(GetGenericSettingsValueOutput)
}

type GetGeoCitiesCity struct {
	Latitude  float64 `pulumi:"latitude"`
	Longitude float64 `pulumi:"longitude"`
	Name      string  `pulumi:"name"`
}

// GetGeoCitiesCityInput is an input type that accepts GetGeoCitiesCityArgs and GetGeoCitiesCityOutput values.
// You can construct a concrete instance of `GetGeoCitiesCityInput` via:
//
//	GetGeoCitiesCityArgs{...}
type GetGeoCitiesCityInput interface {
	pulumi.Input

	ToGetGeoCitiesCityOutput() GetGeoCitiesCityOutput
	ToGetGeoCitiesCityOutputWithContext(context.Context) GetGeoCitiesCityOutput
}

type GetGeoCitiesCityArgs struct {
	Latitude  pulumi.Float64Input `pulumi:"latitude"`
	Longitude pulumi.Float64Input `pulumi:"longitude"`
	Name      pulumi.StringInput  `pulumi:"name"`
}

func (GetGeoCitiesCityArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGeoCitiesCity)(nil)).Elem()
}

func (i GetGeoCitiesCityArgs) ToGetGeoCitiesCityOutput() GetGeoCitiesCityOutput {
	return i.ToGetGeoCitiesCityOutputWithContext(context.Background())
}

func (i GetGeoCitiesCityArgs) ToGetGeoCitiesCityOutputWithContext(ctx context.Context) GetGeoCitiesCityOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGeoCitiesCityOutput)
}

// GetGeoCitiesCityArrayInput is an input type that accepts GetGeoCitiesCityArray and GetGeoCitiesCityArrayOutput values.
// You can construct a concrete instance of `GetGeoCitiesCityArrayInput` via:
//
//	GetGeoCitiesCityArray{ GetGeoCitiesCityArgs{...} }
type GetGeoCitiesCityArrayInput interface {
	pulumi.Input

	ToGetGeoCitiesCityArrayOutput() GetGeoCitiesCityArrayOutput
	ToGetGeoCitiesCityArrayOutputWithContext(context.Context) GetGeoCitiesCityArrayOutput
}

type GetGeoCitiesCityArray []GetGeoCitiesCityInput

func (GetGeoCitiesCityArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGeoCitiesCity)(nil)).Elem()
}

func (i GetGeoCitiesCityArray) ToGetGeoCitiesCityArrayOutput() GetGeoCitiesCityArrayOutput {
	return i.ToGetGeoCitiesCityArrayOutputWithContext(context.Background())
}

func (i GetGeoCitiesCityArray) ToGetGeoCitiesCityArrayOutputWithContext(ctx context.Context) GetGeoCitiesCityArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGeoCitiesCityArrayOutput)
}

type GetGeoCitiesCityOutput struct{ *pulumi.OutputState }

func (GetGeoCitiesCityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGeoCitiesCity)(nil)).Elem()
}

func (o GetGeoCitiesCityOutput) ToGetGeoCitiesCityOutput() GetGeoCitiesCityOutput {
	return o
}

func (o GetGeoCitiesCityOutput) ToGetGeoCitiesCityOutputWithContext(ctx context.Context) GetGeoCitiesCityOutput {
	return o
}

func (o GetGeoCitiesCityOutput) Latitude() pulumi.Float64Output {
	return o.ApplyT(func(v GetGeoCitiesCity) float64 { return v.Latitude }).(pulumi.Float64Output)
}

func (o GetGeoCitiesCityOutput) Longitude() pulumi.Float64Output {
	return o.ApplyT(func(v GetGeoCitiesCity) float64 { return v.Longitude }).(pulumi.Float64Output)
}

func (o GetGeoCitiesCityOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetGeoCitiesCity) string { return v.Name }).(pulumi.StringOutput)
}

type GetGeoCitiesCityArrayOutput struct{ *pulumi.OutputState }

func (GetGeoCitiesCityArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGeoCitiesCity)(nil)).Elem()
}

func (o GetGeoCitiesCityArrayOutput) ToGetGeoCitiesCityArrayOutput() GetGeoCitiesCityArrayOutput {
	return o
}

func (o GetGeoCitiesCityArrayOutput) ToGetGeoCitiesCityArrayOutputWithContext(ctx context.Context) GetGeoCitiesCityArrayOutput {
	return o
}

func (o GetGeoCitiesCityArrayOutput) Index(i pulumi.IntInput) GetGeoCitiesCityOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetGeoCitiesCity {
		return vs[0].([]GetGeoCitiesCity)[vs[1].(int)]
	}).(GetGeoCitiesCityOutput)
}

type GetGeoCountriesCountry struct {
	Code string `pulumi:"code"`
	Name string `pulumi:"name"`
}

// GetGeoCountriesCountryInput is an input type that accepts GetGeoCountriesCountryArgs and GetGeoCountriesCountryOutput values.
// You can construct a concrete instance of `GetGeoCountriesCountryInput` via:
//
//	GetGeoCountriesCountryArgs{...}
type GetGeoCountriesCountryInput interface {
	pulumi.Input

	ToGetGeoCountriesCountryOutput() GetGeoCountriesCountryOutput
	ToGetGeoCountriesCountryOutputWithContext(context.Context) GetGeoCountriesCountryOutput
}

type GetGeoCountriesCountryArgs struct {
	Code pulumi.StringInput `pulumi:"code"`
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetGeoCountriesCountryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGeoCountriesCountry)(nil)).Elem()
}

func (i GetGeoCountriesCountryArgs) ToGetGeoCountriesCountryOutput() GetGeoCountriesCountryOutput {
	return i.ToGetGeoCountriesCountryOutputWithContext(context.Background())
}

func (i GetGeoCountriesCountryArgs) ToGetGeoCountriesCountryOutputWithContext(ctx context.Context) GetGeoCountriesCountryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGeoCountriesCountryOutput)
}

// GetGeoCountriesCountryArrayInput is an input type that accepts GetGeoCountriesCountryArray and GetGeoCountriesCountryArrayOutput values.
// You can construct a concrete instance of `GetGeoCountriesCountryArrayInput` via:
//
//	GetGeoCountriesCountryArray{ GetGeoCountriesCountryArgs{...} }
type GetGeoCountriesCountryArrayInput interface {
	pulumi.Input

	ToGetGeoCountriesCountryArrayOutput() GetGeoCountriesCountryArrayOutput
	ToGetGeoCountriesCountryArrayOutputWithContext(context.Context) GetGeoCountriesCountryArrayOutput
}

type GetGeoCountriesCountryArray []GetGeoCountriesCountryInput

func (GetGeoCountriesCountryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGeoCountriesCountry)(nil)).Elem()
}

func (i GetGeoCountriesCountryArray) ToGetGeoCountriesCountryArrayOutput() GetGeoCountriesCountryArrayOutput {
	return i.ToGetGeoCountriesCountryArrayOutputWithContext(context.Background())
}

func (i GetGeoCountriesCountryArray) ToGetGeoCountriesCountryArrayOutputWithContext(ctx context.Context) GetGeoCountriesCountryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGeoCountriesCountryArrayOutput)
}

type GetGeoCountriesCountryOutput struct{ *pulumi.OutputState }

func (GetGeoCountriesCountryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGeoCountriesCountry)(nil)).Elem()
}

func (o GetGeoCountriesCountryOutput) ToGetGeoCountriesCountryOutput() GetGeoCountriesCountryOutput {
	return o
}

func (o GetGeoCountriesCountryOutput) ToGetGeoCountriesCountryOutputWithContext(ctx context.Context) GetGeoCountriesCountryOutput {
	return o
}

func (o GetGeoCountriesCountryOutput) Code() pulumi.StringOutput {
	return o.ApplyT(func(v GetGeoCountriesCountry) string { return v.Code }).(pulumi.StringOutput)
}

func (o GetGeoCountriesCountryOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetGeoCountriesCountry) string { return v.Name }).(pulumi.StringOutput)
}

type GetGeoCountriesCountryArrayOutput struct{ *pulumi.OutputState }

func (GetGeoCountriesCountryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGeoCountriesCountry)(nil)).Elem()
}

func (o GetGeoCountriesCountryArrayOutput) ToGetGeoCountriesCountryArrayOutput() GetGeoCountriesCountryArrayOutput {
	return o
}

func (o GetGeoCountriesCountryArrayOutput) ToGetGeoCountriesCountryArrayOutputWithContext(ctx context.Context) GetGeoCountriesCountryArrayOutput {
	return o
}

func (o GetGeoCountriesCountryArrayOutput) Index(i pulumi.IntInput) GetGeoCountriesCountryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetGeoCountriesCountry {
		return vs[0].([]GetGeoCountriesCountry)[vs[1].(int)]
	}).(GetGeoCountriesCountryOutput)
}

type GetGeoRegionsRegion struct {
	Code string `pulumi:"code"`
	Name string `pulumi:"name"`
}

// GetGeoRegionsRegionInput is an input type that accepts GetGeoRegionsRegionArgs and GetGeoRegionsRegionOutput values.
// You can construct a concrete instance of `GetGeoRegionsRegionInput` via:
//
//	GetGeoRegionsRegionArgs{...}
type GetGeoRegionsRegionInput interface {
	pulumi.Input

	ToGetGeoRegionsRegionOutput() GetGeoRegionsRegionOutput
	ToGetGeoRegionsRegionOutputWithContext(context.Context) GetGeoRegionsRegionOutput
}

type GetGeoRegionsRegionArgs struct {
	Code pulumi.StringInput `pulumi:"code"`
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetGeoRegionsRegionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGeoRegionsRegion)(nil)).Elem()
}

func (i GetGeoRegionsRegionArgs) ToGetGeoRegionsRegionOutput() GetGeoRegionsRegionOutput {
	return i.ToGetGeoRegionsRegionOutputWithContext(context.Background())
}

func (i GetGeoRegionsRegionArgs) ToGetGeoRegionsRegionOutputWithContext(ctx context.Context) GetGeoRegionsRegionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGeoRegionsRegionOutput)
}

// GetGeoRegionsRegionArrayInput is an input type that accepts GetGeoRegionsRegionArray and GetGeoRegionsRegionArrayOutput values.
// You can construct a concrete instance of `GetGeoRegionsRegionArrayInput` via:
//
//	GetGeoRegionsRegionArray{ GetGeoRegionsRegionArgs{...} }
type GetGeoRegionsRegionArrayInput interface {
	pulumi.Input

	ToGetGeoRegionsRegionArrayOutput() GetGeoRegionsRegionArrayOutput
	ToGetGeoRegionsRegionArrayOutputWithContext(context.Context) GetGeoRegionsRegionArrayOutput
}

type GetGeoRegionsRegionArray []GetGeoRegionsRegionInput

func (GetGeoRegionsRegionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGeoRegionsRegion)(nil)).Elem()
}

func (i GetGeoRegionsRegionArray) ToGetGeoRegionsRegionArrayOutput() GetGeoRegionsRegionArrayOutput {
	return i.ToGetGeoRegionsRegionArrayOutputWithContext(context.Background())
}

func (i GetGeoRegionsRegionArray) ToGetGeoRegionsRegionArrayOutputWithContext(ctx context.Context) GetGeoRegionsRegionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGeoRegionsRegionArrayOutput)
}

type GetGeoRegionsRegionOutput struct{ *pulumi.OutputState }

func (GetGeoRegionsRegionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGeoRegionsRegion)(nil)).Elem()
}

func (o GetGeoRegionsRegionOutput) ToGetGeoRegionsRegionOutput() GetGeoRegionsRegionOutput {
	return o
}

func (o GetGeoRegionsRegionOutput) ToGetGeoRegionsRegionOutputWithContext(ctx context.Context) GetGeoRegionsRegionOutput {
	return o
}

func (o GetGeoRegionsRegionOutput) Code() pulumi.StringOutput {
	return o.ApplyT(func(v GetGeoRegionsRegion) string { return v.Code }).(pulumi.StringOutput)
}

func (o GetGeoRegionsRegionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetGeoRegionsRegion) string { return v.Name }).(pulumi.StringOutput)
}

type GetGeoRegionsRegionArrayOutput struct{ *pulumi.OutputState }

func (GetGeoRegionsRegionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGeoRegionsRegion)(nil)).Elem()
}

func (o GetGeoRegionsRegionArrayOutput) ToGetGeoRegionsRegionArrayOutput() GetGeoRegionsRegionArrayOutput {
	return o
}

func (o GetGeoRegionsRegionArrayOutput) ToGetGeoRegionsRegionArrayOutputWithContext(ctx context.Context) GetGeoRegionsRegionArrayOutput {
	return o
}

func (o GetGeoRegionsRegionArrayOutput) Index(i pulumi.IntInput) GetGeoRegionsRegionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetGeoRegionsRegion {
		return vs[0].([]GetGeoRegionsRegion)[vs[1].(int)]
	}).(GetGeoRegionsRegionOutput)
}

type GetHubItemsItem struct {
	// The activation link for a technology
	ActivationLink string `pulumi:"activationLink"`
	// The unique ID used by the artifacts contained in releases
	ArtifactId string `pulumi:"artifactId"`
	// URL for the author's logo
	AuthorLogo string `pulumi:"authorLogo"`
	// Name of the author of the item
	AuthorName string `pulumi:"authorName"`
	// Checks if the item is compatible with the cluster version
	ClusterCompatible bool `pulumi:"clusterCompatible"`
	// Whether or not the item is planned to be released soon
	ComingSoon bool `pulumi:"comingSoon"`
	// Description of the item
	Description string `pulumi:"description"`
	// An absolute link to the documentation page of this item
	DocumentationLink string `pulumi:"documentationLink"`
	// Whether or not the details call will contain description blocks
	HasDescriptionBlocks bool `pulumi:"hasDescriptionBlocks"`
	// Unique Id of the item
	ItemId string `pulumi:"itemId"`
	// The logo of the item. Can be a URL or Base64 encoded. Intended for HTML tags
	Logo string `pulumi:"logo"`
	// An absolute link to the marketing page of this item
	MarketingLink string `pulumi:"marketingLink"`
	// Name of the item
	Name string `pulumi:"name"`
	// The reason why the item is not compatible with the cluster version
	NotCompatibleReason string `pulumi:"notCompatibleReason"`
	// Grouping of items with keywords
	Tags []string `pulumi:"tags"`
	// Represents the type of item. It can be `TECHNOLOGY`, `EXTENSION1` or `EXTENSION2`
	Type string `pulumi:"type"`
}

// GetHubItemsItemInput is an input type that accepts GetHubItemsItemArgs and GetHubItemsItemOutput values.
// You can construct a concrete instance of `GetHubItemsItemInput` via:
//
//	GetHubItemsItemArgs{...}
type GetHubItemsItemInput interface {
	pulumi.Input

	ToGetHubItemsItemOutput() GetHubItemsItemOutput
	ToGetHubItemsItemOutputWithContext(context.Context) GetHubItemsItemOutput
}

type GetHubItemsItemArgs struct {
	// The activation link for a technology
	ActivationLink pulumi.StringInput `pulumi:"activationLink"`
	// The unique ID used by the artifacts contained in releases
	ArtifactId pulumi.StringInput `pulumi:"artifactId"`
	// URL for the author's logo
	AuthorLogo pulumi.StringInput `pulumi:"authorLogo"`
	// Name of the author of the item
	AuthorName pulumi.StringInput `pulumi:"authorName"`
	// Checks if the item is compatible with the cluster version
	ClusterCompatible pulumi.BoolInput `pulumi:"clusterCompatible"`
	// Whether or not the item is planned to be released soon
	ComingSoon pulumi.BoolInput `pulumi:"comingSoon"`
	// Description of the item
	Description pulumi.StringInput `pulumi:"description"`
	// An absolute link to the documentation page of this item
	DocumentationLink pulumi.StringInput `pulumi:"documentationLink"`
	// Whether or not the details call will contain description blocks
	HasDescriptionBlocks pulumi.BoolInput `pulumi:"hasDescriptionBlocks"`
	// Unique Id of the item
	ItemId pulumi.StringInput `pulumi:"itemId"`
	// The logo of the item. Can be a URL or Base64 encoded. Intended for HTML tags
	Logo pulumi.StringInput `pulumi:"logo"`
	// An absolute link to the marketing page of this item
	MarketingLink pulumi.StringInput `pulumi:"marketingLink"`
	// Name of the item
	Name pulumi.StringInput `pulumi:"name"`
	// The reason why the item is not compatible with the cluster version
	NotCompatibleReason pulumi.StringInput `pulumi:"notCompatibleReason"`
	// Grouping of items with keywords
	Tags pulumi.StringArrayInput `pulumi:"tags"`
	// Represents the type of item. It can be `TECHNOLOGY`, `EXTENSION1` or `EXTENSION2`
	Type pulumi.StringInput `pulumi:"type"`
}

func (GetHubItemsItemArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHubItemsItem)(nil)).Elem()
}

func (i GetHubItemsItemArgs) ToGetHubItemsItemOutput() GetHubItemsItemOutput {
	return i.ToGetHubItemsItemOutputWithContext(context.Background())
}

func (i GetHubItemsItemArgs) ToGetHubItemsItemOutputWithContext(ctx context.Context) GetHubItemsItemOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetHubItemsItemOutput)
}

// GetHubItemsItemArrayInput is an input type that accepts GetHubItemsItemArray and GetHubItemsItemArrayOutput values.
// You can construct a concrete instance of `GetHubItemsItemArrayInput` via:
//
//	GetHubItemsItemArray{ GetHubItemsItemArgs{...} }
type GetHubItemsItemArrayInput interface {
	pulumi.Input

	ToGetHubItemsItemArrayOutput() GetHubItemsItemArrayOutput
	ToGetHubItemsItemArrayOutputWithContext(context.Context) GetHubItemsItemArrayOutput
}

type GetHubItemsItemArray []GetHubItemsItemInput

func (GetHubItemsItemArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetHubItemsItem)(nil)).Elem()
}

func (i GetHubItemsItemArray) ToGetHubItemsItemArrayOutput() GetHubItemsItemArrayOutput {
	return i.ToGetHubItemsItemArrayOutputWithContext(context.Background())
}

func (i GetHubItemsItemArray) ToGetHubItemsItemArrayOutputWithContext(ctx context.Context) GetHubItemsItemArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetHubItemsItemArrayOutput)
}

type GetHubItemsItemOutput struct{ *pulumi.OutputState }

func (GetHubItemsItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHubItemsItem)(nil)).Elem()
}

func (o GetHubItemsItemOutput) ToGetHubItemsItemOutput() GetHubItemsItemOutput {
	return o
}

func (o GetHubItemsItemOutput) ToGetHubItemsItemOutputWithContext(ctx context.Context) GetHubItemsItemOutput {
	return o
}

// The activation link for a technology
func (o GetHubItemsItemOutput) ActivationLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.ActivationLink }).(pulumi.StringOutput)
}

// The unique ID used by the artifacts contained in releases
func (o GetHubItemsItemOutput) ArtifactId() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.ArtifactId }).(pulumi.StringOutput)
}

// URL for the author's logo
func (o GetHubItemsItemOutput) AuthorLogo() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.AuthorLogo }).(pulumi.StringOutput)
}

// Name of the author of the item
func (o GetHubItemsItemOutput) AuthorName() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.AuthorName }).(pulumi.StringOutput)
}

// Checks if the item is compatible with the cluster version
func (o GetHubItemsItemOutput) ClusterCompatible() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHubItemsItem) bool { return v.ClusterCompatible }).(pulumi.BoolOutput)
}

// Whether or not the item is planned to be released soon
func (o GetHubItemsItemOutput) ComingSoon() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHubItemsItem) bool { return v.ComingSoon }).(pulumi.BoolOutput)
}

// Description of the item
func (o GetHubItemsItemOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Description }).(pulumi.StringOutput)
}

// An absolute link to the documentation page of this item
func (o GetHubItemsItemOutput) DocumentationLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.DocumentationLink }).(pulumi.StringOutput)
}

// Whether or not the details call will contain description blocks
func (o GetHubItemsItemOutput) HasDescriptionBlocks() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHubItemsItem) bool { return v.HasDescriptionBlocks }).(pulumi.BoolOutput)
}

// Unique Id of the item
func (o GetHubItemsItemOutput) ItemId() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.ItemId }).(pulumi.StringOutput)
}

// The logo of the item. Can be a URL or Base64 encoded. Intended for HTML tags
func (o GetHubItemsItemOutput) Logo() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Logo }).(pulumi.StringOutput)
}

// An absolute link to the marketing page of this item
func (o GetHubItemsItemOutput) MarketingLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.MarketingLink }).(pulumi.StringOutput)
}

// Name of the item
func (o GetHubItemsItemOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Name }).(pulumi.StringOutput)
}

// The reason why the item is not compatible with the cluster version
func (o GetHubItemsItemOutput) NotCompatibleReason() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.NotCompatibleReason }).(pulumi.StringOutput)
}

// Grouping of items with keywords
func (o GetHubItemsItemOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetHubItemsItem) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// Represents the type of item. It can be `TECHNOLOGY`, `EXTENSION1` or `EXTENSION2`
func (o GetHubItemsItemOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetHubItemsItem) string { return v.Type }).(pulumi.StringOutput)
}

type GetHubItemsItemArrayOutput struct{ *pulumi.OutputState }

func (GetHubItemsItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetHubItemsItem)(nil)).Elem()
}

func (o GetHubItemsItemArrayOutput) ToGetHubItemsItemArrayOutput() GetHubItemsItemArrayOutput {
	return o
}

func (o GetHubItemsItemArrayOutput) ToGetHubItemsItemArrayOutputWithContext(ctx context.Context) GetHubItemsItemArrayOutput {
	return o
}

func (o GetHubItemsItemArrayOutput) Index(i pulumi.IntInput) GetHubItemsItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetHubItemsItem {
		return vs[0].([]GetHubItemsItem)[vs[1].(int)]
	}).(GetHubItemsItemOutput)
}

type GetIamPoliciesPolicy struct {
	// The account UUID the policy is defined for
	Account *string `pulumi:"account"`
	// The environment ID the policy is defined for
	Environment *string `pulumi:"environment"`
	// `true` if this is a global policy`
	Global *bool  `pulumi:"global"`
	Id     string `pulumi:"id"`
	// The name of the policy
	Name string `pulumi:"name"`
	// The UUID of the policy
	Uuid string `pulumi:"uuid"`
}

// GetIamPoliciesPolicyInput is an input type that accepts GetIamPoliciesPolicyArgs and GetIamPoliciesPolicyOutput values.
// You can construct a concrete instance of `GetIamPoliciesPolicyInput` via:
//
//	GetIamPoliciesPolicyArgs{...}
type GetIamPoliciesPolicyInput interface {
	pulumi.Input

	ToGetIamPoliciesPolicyOutput() GetIamPoliciesPolicyOutput
	ToGetIamPoliciesPolicyOutputWithContext(context.Context) GetIamPoliciesPolicyOutput
}

type GetIamPoliciesPolicyArgs struct {
	// The account UUID the policy is defined for
	Account pulumi.StringPtrInput `pulumi:"account"`
	// The environment ID the policy is defined for
	Environment pulumi.StringPtrInput `pulumi:"environment"`
	// `true` if this is a global policy`
	Global pulumi.BoolPtrInput `pulumi:"global"`
	Id     pulumi.StringInput  `pulumi:"id"`
	// The name of the policy
	Name pulumi.StringInput `pulumi:"name"`
	// The UUID of the policy
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetIamPoliciesPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamPoliciesPolicy)(nil)).Elem()
}

func (i GetIamPoliciesPolicyArgs) ToGetIamPoliciesPolicyOutput() GetIamPoliciesPolicyOutput {
	return i.ToGetIamPoliciesPolicyOutputWithContext(context.Background())
}

func (i GetIamPoliciesPolicyArgs) ToGetIamPoliciesPolicyOutputWithContext(ctx context.Context) GetIamPoliciesPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetIamPoliciesPolicyOutput)
}

// GetIamPoliciesPolicyArrayInput is an input type that accepts GetIamPoliciesPolicyArray and GetIamPoliciesPolicyArrayOutput values.
// You can construct a concrete instance of `GetIamPoliciesPolicyArrayInput` via:
//
//	GetIamPoliciesPolicyArray{ GetIamPoliciesPolicyArgs{...} }
type GetIamPoliciesPolicyArrayInput interface {
	pulumi.Input

	ToGetIamPoliciesPolicyArrayOutput() GetIamPoliciesPolicyArrayOutput
	ToGetIamPoliciesPolicyArrayOutputWithContext(context.Context) GetIamPoliciesPolicyArrayOutput
}

type GetIamPoliciesPolicyArray []GetIamPoliciesPolicyInput

func (GetIamPoliciesPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetIamPoliciesPolicy)(nil)).Elem()
}

func (i GetIamPoliciesPolicyArray) ToGetIamPoliciesPolicyArrayOutput() GetIamPoliciesPolicyArrayOutput {
	return i.ToGetIamPoliciesPolicyArrayOutputWithContext(context.Background())
}

func (i GetIamPoliciesPolicyArray) ToGetIamPoliciesPolicyArrayOutputWithContext(ctx context.Context) GetIamPoliciesPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetIamPoliciesPolicyArrayOutput)
}

type GetIamPoliciesPolicyOutput struct{ *pulumi.OutputState }

func (GetIamPoliciesPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamPoliciesPolicy)(nil)).Elem()
}

func (o GetIamPoliciesPolicyOutput) ToGetIamPoliciesPolicyOutput() GetIamPoliciesPolicyOutput {
	return o
}

func (o GetIamPoliciesPolicyOutput) ToGetIamPoliciesPolicyOutputWithContext(ctx context.Context) GetIamPoliciesPolicyOutput {
	return o
}

// The account UUID the policy is defined for
func (o GetIamPoliciesPolicyOutput) Account() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIamPoliciesPolicy) *string { return v.Account }).(pulumi.StringPtrOutput)
}

// The environment ID the policy is defined for
func (o GetIamPoliciesPolicyOutput) Environment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIamPoliciesPolicy) *string { return v.Environment }).(pulumi.StringPtrOutput)
}

// `true` if this is a global policy`
func (o GetIamPoliciesPolicyOutput) Global() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetIamPoliciesPolicy) *bool { return v.Global }).(pulumi.BoolPtrOutput)
}

func (o GetIamPoliciesPolicyOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamPoliciesPolicy) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the policy
func (o GetIamPoliciesPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamPoliciesPolicy) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the policy
func (o GetIamPoliciesPolicyOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamPoliciesPolicy) string { return v.Uuid }).(pulumi.StringOutput)
}

type GetIamPoliciesPolicyArrayOutput struct{ *pulumi.OutputState }

func (GetIamPoliciesPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetIamPoliciesPolicy)(nil)).Elem()
}

func (o GetIamPoliciesPolicyArrayOutput) ToGetIamPoliciesPolicyArrayOutput() GetIamPoliciesPolicyArrayOutput {
	return o
}

func (o GetIamPoliciesPolicyArrayOutput) ToGetIamPoliciesPolicyArrayOutputWithContext(ctx context.Context) GetIamPoliciesPolicyArrayOutput {
	return o
}

func (o GetIamPoliciesPolicyArrayOutput) Index(i pulumi.IntInput) GetIamPoliciesPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetIamPoliciesPolicy {
		return vs[0].([]GetIamPoliciesPolicy)[vs[1].(int)]
	}).(GetIamPoliciesPolicyOutput)
}

type GetManagementZonesValue struct {
	// The description of the Management Zone
	Description string `pulumi:"description"`
	// The ID of the Management Zone when referred to as a Settings 2.0 resource (e.g. from within `SlackNotification`)
	Id string `pulumi:"id"`
	// The ID of the Management Zone when referred to as a Configuration API resource (e.g. from within `Notification`)
	LegacyId string `pulumi:"legacyId"`
	// The name of the Management Zone
	Name string `pulumi:"name"`
}

// GetManagementZonesValueInput is an input type that accepts GetManagementZonesValueArgs and GetManagementZonesValueOutput values.
// You can construct a concrete instance of `GetManagementZonesValueInput` via:
//
//	GetManagementZonesValueArgs{...}
type GetManagementZonesValueInput interface {
	pulumi.Input

	ToGetManagementZonesValueOutput() GetManagementZonesValueOutput
	ToGetManagementZonesValueOutputWithContext(context.Context) GetManagementZonesValueOutput
}

type GetManagementZonesValueArgs struct {
	// The description of the Management Zone
	Description pulumi.StringInput `pulumi:"description"`
	// The ID of the Management Zone when referred to as a Settings 2.0 resource (e.g. from within `SlackNotification`)
	Id pulumi.StringInput `pulumi:"id"`
	// The ID of the Management Zone when referred to as a Configuration API resource (e.g. from within `Notification`)
	LegacyId pulumi.StringInput `pulumi:"legacyId"`
	// The name of the Management Zone
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetManagementZonesValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetManagementZonesValue)(nil)).Elem()
}

func (i GetManagementZonesValueArgs) ToGetManagementZonesValueOutput() GetManagementZonesValueOutput {
	return i.ToGetManagementZonesValueOutputWithContext(context.Background())
}

func (i GetManagementZonesValueArgs) ToGetManagementZonesValueOutputWithContext(ctx context.Context) GetManagementZonesValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetManagementZonesValueOutput)
}

// GetManagementZonesValueArrayInput is an input type that accepts GetManagementZonesValueArray and GetManagementZonesValueArrayOutput values.
// You can construct a concrete instance of `GetManagementZonesValueArrayInput` via:
//
//	GetManagementZonesValueArray{ GetManagementZonesValueArgs{...} }
type GetManagementZonesValueArrayInput interface {
	pulumi.Input

	ToGetManagementZonesValueArrayOutput() GetManagementZonesValueArrayOutput
	ToGetManagementZonesValueArrayOutputWithContext(context.Context) GetManagementZonesValueArrayOutput
}

type GetManagementZonesValueArray []GetManagementZonesValueInput

func (GetManagementZonesValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetManagementZonesValue)(nil)).Elem()
}

func (i GetManagementZonesValueArray) ToGetManagementZonesValueArrayOutput() GetManagementZonesValueArrayOutput {
	return i.ToGetManagementZonesValueArrayOutputWithContext(context.Background())
}

func (i GetManagementZonesValueArray) ToGetManagementZonesValueArrayOutputWithContext(ctx context.Context) GetManagementZonesValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetManagementZonesValueArrayOutput)
}

type GetManagementZonesValueOutput struct{ *pulumi.OutputState }

func (GetManagementZonesValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetManagementZonesValue)(nil)).Elem()
}

func (o GetManagementZonesValueOutput) ToGetManagementZonesValueOutput() GetManagementZonesValueOutput {
	return o
}

func (o GetManagementZonesValueOutput) ToGetManagementZonesValueOutputWithContext(ctx context.Context) GetManagementZonesValueOutput {
	return o
}

// The description of the Management Zone
func (o GetManagementZonesValueOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.Description }).(pulumi.StringOutput)
}

// The ID of the Management Zone when referred to as a Settings 2.0 resource (e.g. from within `SlackNotification`)
func (o GetManagementZonesValueOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the Management Zone when referred to as a Configuration API resource (e.g. from within `Notification`)
func (o GetManagementZonesValueOutput) LegacyId() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.LegacyId }).(pulumi.StringOutput)
}

// The name of the Management Zone
func (o GetManagementZonesValueOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagementZonesValue) string { return v.Name }).(pulumi.StringOutput)
}

type GetManagementZonesValueArrayOutput struct{ *pulumi.OutputState }

func (GetManagementZonesValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetManagementZonesValue)(nil)).Elem()
}

func (o GetManagementZonesValueArrayOutput) ToGetManagementZonesValueArrayOutput() GetManagementZonesValueArrayOutput {
	return o
}

func (o GetManagementZonesValueArrayOutput) ToGetManagementZonesValueArrayOutputWithContext(ctx context.Context) GetManagementZonesValueArrayOutput {
	return o
}

func (o GetManagementZonesValueArrayOutput) Index(i pulumi.IntInput) GetManagementZonesValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetManagementZonesValue {
		return vs[0].([]GetManagementZonesValue)[vs[1].(int)]
	}).(GetManagementZonesValueOutput)
}

type GetPlatformSloTemplatesTemplate struct {
	// ID of the SLO objective template
	Id string `pulumi:"id"`
	// Name of the SLO objective template
	Name string `pulumi:"name"`
}

// GetPlatformSloTemplatesTemplateInput is an input type that accepts GetPlatformSloTemplatesTemplateArgs and GetPlatformSloTemplatesTemplateOutput values.
// You can construct a concrete instance of `GetPlatformSloTemplatesTemplateInput` via:
//
//	GetPlatformSloTemplatesTemplateArgs{...}
type GetPlatformSloTemplatesTemplateInput interface {
	pulumi.Input

	ToGetPlatformSloTemplatesTemplateOutput() GetPlatformSloTemplatesTemplateOutput
	ToGetPlatformSloTemplatesTemplateOutputWithContext(context.Context) GetPlatformSloTemplatesTemplateOutput
}

type GetPlatformSloTemplatesTemplateArgs struct {
	// ID of the SLO objective template
	Id pulumi.StringInput `pulumi:"id"`
	// Name of the SLO objective template
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetPlatformSloTemplatesTemplateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPlatformSloTemplatesTemplate)(nil)).Elem()
}

func (i GetPlatformSloTemplatesTemplateArgs) ToGetPlatformSloTemplatesTemplateOutput() GetPlatformSloTemplatesTemplateOutput {
	return i.ToGetPlatformSloTemplatesTemplateOutputWithContext(context.Background())
}

func (i GetPlatformSloTemplatesTemplateArgs) ToGetPlatformSloTemplatesTemplateOutputWithContext(ctx context.Context) GetPlatformSloTemplatesTemplateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPlatformSloTemplatesTemplateOutput)
}

// GetPlatformSloTemplatesTemplateArrayInput is an input type that accepts GetPlatformSloTemplatesTemplateArray and GetPlatformSloTemplatesTemplateArrayOutput values.
// You can construct a concrete instance of `GetPlatformSloTemplatesTemplateArrayInput` via:
//
//	GetPlatformSloTemplatesTemplateArray{ GetPlatformSloTemplatesTemplateArgs{...} }
type GetPlatformSloTemplatesTemplateArrayInput interface {
	pulumi.Input

	ToGetPlatformSloTemplatesTemplateArrayOutput() GetPlatformSloTemplatesTemplateArrayOutput
	ToGetPlatformSloTemplatesTemplateArrayOutputWithContext(context.Context) GetPlatformSloTemplatesTemplateArrayOutput
}

type GetPlatformSloTemplatesTemplateArray []GetPlatformSloTemplatesTemplateInput

func (GetPlatformSloTemplatesTemplateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPlatformSloTemplatesTemplate)(nil)).Elem()
}

func (i GetPlatformSloTemplatesTemplateArray) ToGetPlatformSloTemplatesTemplateArrayOutput() GetPlatformSloTemplatesTemplateArrayOutput {
	return i.ToGetPlatformSloTemplatesTemplateArrayOutputWithContext(context.Background())
}

func (i GetPlatformSloTemplatesTemplateArray) ToGetPlatformSloTemplatesTemplateArrayOutputWithContext(ctx context.Context) GetPlatformSloTemplatesTemplateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPlatformSloTemplatesTemplateArrayOutput)
}

type GetPlatformSloTemplatesTemplateOutput struct{ *pulumi.OutputState }

func (GetPlatformSloTemplatesTemplateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPlatformSloTemplatesTemplate)(nil)).Elem()
}

func (o GetPlatformSloTemplatesTemplateOutput) ToGetPlatformSloTemplatesTemplateOutput() GetPlatformSloTemplatesTemplateOutput {
	return o
}

func (o GetPlatformSloTemplatesTemplateOutput) ToGetPlatformSloTemplatesTemplateOutputWithContext(ctx context.Context) GetPlatformSloTemplatesTemplateOutput {
	return o
}

// ID of the SLO objective template
func (o GetPlatformSloTemplatesTemplateOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPlatformSloTemplatesTemplate) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the SLO objective template
func (o GetPlatformSloTemplatesTemplateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPlatformSloTemplatesTemplate) string { return v.Name }).(pulumi.StringOutput)
}

type GetPlatformSloTemplatesTemplateArrayOutput struct{ *pulumi.OutputState }

func (GetPlatformSloTemplatesTemplateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPlatformSloTemplatesTemplate)(nil)).Elem()
}

func (o GetPlatformSloTemplatesTemplateArrayOutput) ToGetPlatformSloTemplatesTemplateArrayOutput() GetPlatformSloTemplatesTemplateArrayOutput {
	return o
}

func (o GetPlatformSloTemplatesTemplateArrayOutput) ToGetPlatformSloTemplatesTemplateArrayOutputWithContext(ctx context.Context) GetPlatformSloTemplatesTemplateArrayOutput {
	return o
}

func (o GetPlatformSloTemplatesTemplateArrayOutput) Index(i pulumi.IntInput) GetPlatformSloTemplatesTemplateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPlatformSloTemplatesTemplate {
		return vs[0].([]GetPlatformSloTemplatesTemplate)[vs[1].(int)]
	}).(GetPlatformSloTemplatesTemplateOutput)
}

type GetRemoteEnvironmentsRemoteEnvironment struct {
	// Name
	Name string `pulumi:"name"`
	// Possible Values: `CLUSTER`, `EXTERNAL`, `INTERNAL`
	NetworkScope string `pulumi:"networkScope"`
	// Provide a valid token created on the remote environment.
	Token string `pulumi:"token"`
	// Specify the full URI to the remote environment. Your local environment will have to be able to connect this URI on a network level.
	Uri string `pulumi:"uri"`
}

// GetRemoteEnvironmentsRemoteEnvironmentInput is an input type that accepts GetRemoteEnvironmentsRemoteEnvironmentArgs and GetRemoteEnvironmentsRemoteEnvironmentOutput values.
// You can construct a concrete instance of `GetRemoteEnvironmentsRemoteEnvironmentInput` via:
//
//	GetRemoteEnvironmentsRemoteEnvironmentArgs{...}
type GetRemoteEnvironmentsRemoteEnvironmentInput interface {
	pulumi.Input

	ToGetRemoteEnvironmentsRemoteEnvironmentOutput() GetRemoteEnvironmentsRemoteEnvironmentOutput
	ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(context.Context) GetRemoteEnvironmentsRemoteEnvironmentOutput
}

type GetRemoteEnvironmentsRemoteEnvironmentArgs struct {
	// Name
	Name pulumi.StringInput `pulumi:"name"`
	// Possible Values: `CLUSTER`, `EXTERNAL`, `INTERNAL`
	NetworkScope pulumi.StringInput `pulumi:"networkScope"`
	// Provide a valid token created on the remote environment.
	Token pulumi.StringInput `pulumi:"token"`
	// Specify the full URI to the remote environment. Your local environment will have to be able to connect this URI on a network level.
	Uri pulumi.StringInput `pulumi:"uri"`
}

func (GetRemoteEnvironmentsRemoteEnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArgs) ToGetRemoteEnvironmentsRemoteEnvironmentOutput() GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return i.ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(context.Background())
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArgs) ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRemoteEnvironmentsRemoteEnvironmentOutput)
}

// GetRemoteEnvironmentsRemoteEnvironmentArrayInput is an input type that accepts GetRemoteEnvironmentsRemoteEnvironmentArray and GetRemoteEnvironmentsRemoteEnvironmentArrayOutput values.
// You can construct a concrete instance of `GetRemoteEnvironmentsRemoteEnvironmentArrayInput` via:
//
//	GetRemoteEnvironmentsRemoteEnvironmentArray{ GetRemoteEnvironmentsRemoteEnvironmentArgs{...} }
type GetRemoteEnvironmentsRemoteEnvironmentArrayInput interface {
	pulumi.Input

	ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutput() GetRemoteEnvironmentsRemoteEnvironmentArrayOutput
	ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(context.Context) GetRemoteEnvironmentsRemoteEnvironmentArrayOutput
}

type GetRemoteEnvironmentsRemoteEnvironmentArray []GetRemoteEnvironmentsRemoteEnvironmentInput

func (GetRemoteEnvironmentsRemoteEnvironmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArray) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutput() GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return i.ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(context.Background())
}

func (i GetRemoteEnvironmentsRemoteEnvironmentArray) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRemoteEnvironmentsRemoteEnvironmentArrayOutput)
}

type GetRemoteEnvironmentsRemoteEnvironmentOutput struct{ *pulumi.OutputState }

func (GetRemoteEnvironmentsRemoteEnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) ToGetRemoteEnvironmentsRemoteEnvironmentOutput() GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) ToGetRemoteEnvironmentsRemoteEnvironmentOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return o
}

// Name
func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.Name }).(pulumi.StringOutput)
}

// Possible Values: `CLUSTER`, `EXTERNAL`, `INTERNAL`
func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) NetworkScope() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.NetworkScope }).(pulumi.StringOutput)
}

// Provide a valid token created on the remote environment.
func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.Token }).(pulumi.StringOutput)
}

// Specify the full URI to the remote environment. Your local environment will have to be able to connect this URI on a network level.
func (o GetRemoteEnvironmentsRemoteEnvironmentOutput) Uri() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteEnvironmentsRemoteEnvironment) string { return v.Uri }).(pulumi.StringOutput)
}

type GetRemoteEnvironmentsRemoteEnvironmentArrayOutput struct{ *pulumi.OutputState }

func (GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRemoteEnvironmentsRemoteEnvironment)(nil)).Elem()
}

func (o GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutput() GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) ToGetRemoteEnvironmentsRemoteEnvironmentArrayOutputWithContext(ctx context.Context) GetRemoteEnvironmentsRemoteEnvironmentArrayOutput {
	return o
}

func (o GetRemoteEnvironmentsRemoteEnvironmentArrayOutput) Index(i pulumi.IntInput) GetRemoteEnvironmentsRemoteEnvironmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetRemoteEnvironmentsRemoteEnvironment {
		return vs[0].([]GetRemoteEnvironmentsRemoteEnvironment)[vs[1].(int)]
	}).(GetRemoteEnvironmentsRemoteEnvironmentOutput)
}

type GetSyntheticLocationsLocations struct {
	// The cloud provider where the location is hosted.
	CloudPlatform string `pulumi:"cloudPlatform"`
	// The unique ID of the location
	EntityId *string `pulumi:"entityId"`
	// The Dynatrace GeoLocation ID of the location
	GeoLocationId string `pulumi:"geoLocationId"`
	// The list of IP addresses assigned to the location.
	//
	//  Only applicable to `PUBLIC` locations
	Ips []string `pulumi:"ips"`
	// The name of the location
	Name *string `pulumi:"name"`
	// The release stage of the location
	Stage string `pulumi:"stage"`
	// The status of the location:
	//
	// * `ENABLED`: The location is displayed as active in the UI. You can assign monitors to the location.
	// * `DISABLED`: The location is displayed as inactive in the UI. You can't assign monitors to the location. Monitors already assigned to the location will stay there and will be executed from the location.
	// * `HIDDEN`: The location is not displayed in the UI. You can't assign monitors to the location. You can only set location as `HIDDEN` when no monitor is assigned to it
	Status string `pulumi:"status"`
	// The type of the location. Supported values are `PUBLIC`, `PRIVATE` and `CLUSTER`
	Type *string `pulumi:"type"`
}

// GetSyntheticLocationsLocationsInput is an input type that accepts GetSyntheticLocationsLocationsArgs and GetSyntheticLocationsLocationsOutput values.
// You can construct a concrete instance of `GetSyntheticLocationsLocationsInput` via:
//
//	GetSyntheticLocationsLocationsArgs{...}
type GetSyntheticLocationsLocationsInput interface {
	pulumi.Input

	ToGetSyntheticLocationsLocationsOutput() GetSyntheticLocationsLocationsOutput
	ToGetSyntheticLocationsLocationsOutputWithContext(context.Context) GetSyntheticLocationsLocationsOutput
}

type GetSyntheticLocationsLocationsArgs struct {
	// The cloud provider where the location is hosted.
	CloudPlatform pulumi.StringInput `pulumi:"cloudPlatform"`
	// The unique ID of the location
	EntityId pulumi.StringPtrInput `pulumi:"entityId"`
	// The Dynatrace GeoLocation ID of the location
	GeoLocationId pulumi.StringInput `pulumi:"geoLocationId"`
	// The list of IP addresses assigned to the location.
	//
	//  Only applicable to `PUBLIC` locations
	Ips pulumi.StringArrayInput `pulumi:"ips"`
	// The name of the location
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The release stage of the location
	Stage pulumi.StringInput `pulumi:"stage"`
	// The status of the location:
	//
	// * `ENABLED`: The location is displayed as active in the UI. You can assign monitors to the location.
	// * `DISABLED`: The location is displayed as inactive in the UI. You can't assign monitors to the location. Monitors already assigned to the location will stay there and will be executed from the location.
	// * `HIDDEN`: The location is not displayed in the UI. You can't assign monitors to the location. You can only set location as `HIDDEN` when no monitor is assigned to it
	Status pulumi.StringInput `pulumi:"status"`
	// The type of the location. Supported values are `PUBLIC`, `PRIVATE` and `CLUSTER`
	Type pulumi.StringPtrInput `pulumi:"type"`
}

func (GetSyntheticLocationsLocationsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticLocationsLocations)(nil)).Elem()
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsOutput() GetSyntheticLocationsLocationsOutput {
	return i.ToGetSyntheticLocationsLocationsOutputWithContext(context.Background())
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticLocationsLocationsOutput)
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return i.ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Background())
}

func (i GetSyntheticLocationsLocationsArgs) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticLocationsLocationsOutput).ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx)
}

// GetSyntheticLocationsLocationsPtrInput is an input type that accepts GetSyntheticLocationsLocationsArgs, GetSyntheticLocationsLocationsPtr and GetSyntheticLocationsLocationsPtrOutput values.
// You can construct a concrete instance of `GetSyntheticLocationsLocationsPtrInput` via:
//
//	        GetSyntheticLocationsLocationsArgs{...}
//
//	or:
//
//	        nil
type GetSyntheticLocationsLocationsPtrInput interface {
	pulumi.Input

	ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput
	ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Context) GetSyntheticLocationsLocationsPtrOutput
}

type getSyntheticLocationsLocationsPtrType GetSyntheticLocationsLocationsArgs

func GetSyntheticLocationsLocationsPtr(v *GetSyntheticLocationsLocationsArgs) GetSyntheticLocationsLocationsPtrInput {
	return (*getSyntheticLocationsLocationsPtrType)(v)
}

func (*getSyntheticLocationsLocationsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetSyntheticLocationsLocations)(nil)).Elem()
}

func (i *getSyntheticLocationsLocationsPtrType) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return i.ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Background())
}

func (i *getSyntheticLocationsLocationsPtrType) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticLocationsLocationsPtrOutput)
}

type GetSyntheticLocationsLocationsOutput struct{ *pulumi.OutputState }

func (GetSyntheticLocationsLocationsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticLocationsLocations)(nil)).Elem()
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsOutput() GetSyntheticLocationsLocationsOutput {
	return o
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsOutput {
	return o
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return o.ToGetSyntheticLocationsLocationsPtrOutputWithContext(context.Background())
}

func (o GetSyntheticLocationsLocationsOutput) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetSyntheticLocationsLocations) *GetSyntheticLocationsLocations {
		return &v
	}).(GetSyntheticLocationsLocationsPtrOutput)
}

// The cloud provider where the location is hosted.
func (o GetSyntheticLocationsLocationsOutput) CloudPlatform() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.CloudPlatform }).(pulumi.StringOutput)
}

// The unique ID of the location
func (o GetSyntheticLocationsLocationsOutput) EntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) *string { return v.EntityId }).(pulumi.StringPtrOutput)
}

// The Dynatrace GeoLocation ID of the location
func (o GetSyntheticLocationsLocationsOutput) GeoLocationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.GeoLocationId }).(pulumi.StringOutput)
}

// The list of IP addresses assigned to the location.
//
//	Only applicable to `PUBLIC` locations
func (o GetSyntheticLocationsLocationsOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

// The name of the location
func (o GetSyntheticLocationsLocationsOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The release stage of the location
func (o GetSyntheticLocationsLocationsOutput) Stage() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.Stage }).(pulumi.StringOutput)
}

// The status of the location:
//
// * `ENABLED`: The location is displayed as active in the UI. You can assign monitors to the location.
// * `DISABLED`: The location is displayed as inactive in the UI. You can't assign monitors to the location. Monitors already assigned to the location will stay there and will be executed from the location.
// * `HIDDEN`: The location is not displayed in the UI. You can't assign monitors to the location. You can only set location as `HIDDEN` when no monitor is assigned to it
func (o GetSyntheticLocationsLocationsOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) string { return v.Status }).(pulumi.StringOutput)
}

// The type of the location. Supported values are `PUBLIC`, `PRIVATE` and `CLUSTER`
func (o GetSyntheticLocationsLocationsOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSyntheticLocationsLocations) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type GetSyntheticLocationsLocationsPtrOutput struct{ *pulumi.OutputState }

func (GetSyntheticLocationsLocationsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetSyntheticLocationsLocations)(nil)).Elem()
}

func (o GetSyntheticLocationsLocationsPtrOutput) ToGetSyntheticLocationsLocationsPtrOutput() GetSyntheticLocationsLocationsPtrOutput {
	return o
}

func (o GetSyntheticLocationsLocationsPtrOutput) ToGetSyntheticLocationsLocationsPtrOutputWithContext(ctx context.Context) GetSyntheticLocationsLocationsPtrOutput {
	return o
}

func (o GetSyntheticLocationsLocationsPtrOutput) Elem() GetSyntheticLocationsLocationsOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) GetSyntheticLocationsLocations {
		if v != nil {
			return *v
		}
		var ret GetSyntheticLocationsLocations
		return ret
	}).(GetSyntheticLocationsLocationsOutput)
}

// The cloud provider where the location is hosted.
func (o GetSyntheticLocationsLocationsPtrOutput) CloudPlatform() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.CloudPlatform
	}).(pulumi.StringPtrOutput)
}

// The unique ID of the location
func (o GetSyntheticLocationsLocationsPtrOutput) EntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return v.EntityId
	}).(pulumi.StringPtrOutput)
}

// The Dynatrace GeoLocation ID of the location
func (o GetSyntheticLocationsLocationsPtrOutput) GeoLocationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.GeoLocationId
	}).(pulumi.StringPtrOutput)
}

// The list of IP addresses assigned to the location.
//
//	Only applicable to `PUBLIC` locations
func (o GetSyntheticLocationsLocationsPtrOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) []string {
		if v == nil {
			return nil
		}
		return v.Ips
	}).(pulumi.StringArrayOutput)
}

// The name of the location
func (o GetSyntheticLocationsLocationsPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return v.Name
	}).(pulumi.StringPtrOutput)
}

// The release stage of the location
func (o GetSyntheticLocationsLocationsPtrOutput) Stage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.Stage
	}).(pulumi.StringPtrOutput)
}

// The status of the location:
//
// * `ENABLED`: The location is displayed as active in the UI. You can assign monitors to the location.
// * `DISABLED`: The location is displayed as inactive in the UI. You can't assign monitors to the location. Monitors already assigned to the location will stay there and will be executed from the location.
// * `HIDDEN`: The location is not displayed in the UI. You can't assign monitors to the location. You can only set location as `HIDDEN` when no monitor is assigned to it
func (o GetSyntheticLocationsLocationsPtrOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return &v.Status
	}).(pulumi.StringPtrOutput)
}

// The type of the location. Supported values are `PUBLIC`, `PRIVATE` and `CLUSTER`
func (o GetSyntheticLocationsLocationsPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetSyntheticLocationsLocations) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

type GetSyntheticNodesNode struct {
	// The version of the Active Gate
	ActiveGateVersion string `pulumi:"activeGateVersion"`
	// Specifies whether the Active Gate  has the Auto update option enabled
	AutoUpdate bool `pulumi:"autoUpdate"`
	// Specifies whether Browser Monitors are enabled or not
	BrowserMonitors bool `pulumi:"browserMonitors"`
	// The health check status of the synthetic node
	HealthCheckStatus string `pulumi:"healthCheckStatus"`
	// The hostname of a node
	Hostname string `pulumi:"hostname"`
	// The ID of a node for usage within `SyntheticLocation`
	Id string `pulumi:"id"`
	// The known IP addresses of the node
	Ips []string `pulumi:"ips"`
	// Specifies whether the Active Gate has the One Agent routing enabled
	OneAgentRouting bool `pulumi:"oneAgentRouting"`
	// The Active Gate's host operating system
	OperatingSystem string `pulumi:"operatingSystem"`
	// The version of the synthetic player
	PlayerVersion string `pulumi:"playerVersion"`
	// The status of the synthetic node
	Status string `pulumi:"status"`
	// The version of a node
	Version string `pulumi:"version"`
}

// GetSyntheticNodesNodeInput is an input type that accepts GetSyntheticNodesNodeArgs and GetSyntheticNodesNodeOutput values.
// You can construct a concrete instance of `GetSyntheticNodesNodeInput` via:
//
//	GetSyntheticNodesNodeArgs{...}
type GetSyntheticNodesNodeInput interface {
	pulumi.Input

	ToGetSyntheticNodesNodeOutput() GetSyntheticNodesNodeOutput
	ToGetSyntheticNodesNodeOutputWithContext(context.Context) GetSyntheticNodesNodeOutput
}

type GetSyntheticNodesNodeArgs struct {
	// The version of the Active Gate
	ActiveGateVersion pulumi.StringInput `pulumi:"activeGateVersion"`
	// Specifies whether the Active Gate  has the Auto update option enabled
	AutoUpdate pulumi.BoolInput `pulumi:"autoUpdate"`
	// Specifies whether Browser Monitors are enabled or not
	BrowserMonitors pulumi.BoolInput `pulumi:"browserMonitors"`
	// The health check status of the synthetic node
	HealthCheckStatus pulumi.StringInput `pulumi:"healthCheckStatus"`
	// The hostname of a node
	Hostname pulumi.StringInput `pulumi:"hostname"`
	// The ID of a node for usage within `SyntheticLocation`
	Id pulumi.StringInput `pulumi:"id"`
	// The known IP addresses of the node
	Ips pulumi.StringArrayInput `pulumi:"ips"`
	// Specifies whether the Active Gate has the One Agent routing enabled
	OneAgentRouting pulumi.BoolInput `pulumi:"oneAgentRouting"`
	// The Active Gate's host operating system
	OperatingSystem pulumi.StringInput `pulumi:"operatingSystem"`
	// The version of the synthetic player
	PlayerVersion pulumi.StringInput `pulumi:"playerVersion"`
	// The status of the synthetic node
	Status pulumi.StringInput `pulumi:"status"`
	// The version of a node
	Version pulumi.StringInput `pulumi:"version"`
}

func (GetSyntheticNodesNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticNodesNode)(nil)).Elem()
}

func (i GetSyntheticNodesNodeArgs) ToGetSyntheticNodesNodeOutput() GetSyntheticNodesNodeOutput {
	return i.ToGetSyntheticNodesNodeOutputWithContext(context.Background())
}

func (i GetSyntheticNodesNodeArgs) ToGetSyntheticNodesNodeOutputWithContext(ctx context.Context) GetSyntheticNodesNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticNodesNodeOutput)
}

// GetSyntheticNodesNodeArrayInput is an input type that accepts GetSyntheticNodesNodeArray and GetSyntheticNodesNodeArrayOutput values.
// You can construct a concrete instance of `GetSyntheticNodesNodeArrayInput` via:
//
//	GetSyntheticNodesNodeArray{ GetSyntheticNodesNodeArgs{...} }
type GetSyntheticNodesNodeArrayInput interface {
	pulumi.Input

	ToGetSyntheticNodesNodeArrayOutput() GetSyntheticNodesNodeArrayOutput
	ToGetSyntheticNodesNodeArrayOutputWithContext(context.Context) GetSyntheticNodesNodeArrayOutput
}

type GetSyntheticNodesNodeArray []GetSyntheticNodesNodeInput

func (GetSyntheticNodesNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSyntheticNodesNode)(nil)).Elem()
}

func (i GetSyntheticNodesNodeArray) ToGetSyntheticNodesNodeArrayOutput() GetSyntheticNodesNodeArrayOutput {
	return i.ToGetSyntheticNodesNodeArrayOutputWithContext(context.Background())
}

func (i GetSyntheticNodesNodeArray) ToGetSyntheticNodesNodeArrayOutputWithContext(ctx context.Context) GetSyntheticNodesNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSyntheticNodesNodeArrayOutput)
}

type GetSyntheticNodesNodeOutput struct{ *pulumi.OutputState }

func (GetSyntheticNodesNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSyntheticNodesNode)(nil)).Elem()
}

func (o GetSyntheticNodesNodeOutput) ToGetSyntheticNodesNodeOutput() GetSyntheticNodesNodeOutput {
	return o
}

func (o GetSyntheticNodesNodeOutput) ToGetSyntheticNodesNodeOutputWithContext(ctx context.Context) GetSyntheticNodesNodeOutput {
	return o
}

// The version of the Active Gate
func (o GetSyntheticNodesNodeOutput) ActiveGateVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.ActiveGateVersion }).(pulumi.StringOutput)
}

// Specifies whether the Active Gate  has the Auto update option enabled
func (o GetSyntheticNodesNodeOutput) AutoUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) bool { return v.AutoUpdate }).(pulumi.BoolOutput)
}

// Specifies whether Browser Monitors are enabled or not
func (o GetSyntheticNodesNodeOutput) BrowserMonitors() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) bool { return v.BrowserMonitors }).(pulumi.BoolOutput)
}

// The health check status of the synthetic node
func (o GetSyntheticNodesNodeOutput) HealthCheckStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.HealthCheckStatus }).(pulumi.StringOutput)
}

// The hostname of a node
func (o GetSyntheticNodesNodeOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Hostname }).(pulumi.StringOutput)
}

// The ID of a node for usage within `SyntheticLocation`
func (o GetSyntheticNodesNodeOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Id }).(pulumi.StringOutput)
}

// The known IP addresses of the node
func (o GetSyntheticNodesNodeOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

// Specifies whether the Active Gate has the One Agent routing enabled
func (o GetSyntheticNodesNodeOutput) OneAgentRouting() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) bool { return v.OneAgentRouting }).(pulumi.BoolOutput)
}

// The Active Gate's host operating system
func (o GetSyntheticNodesNodeOutput) OperatingSystem() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.OperatingSystem }).(pulumi.StringOutput)
}

// The version of the synthetic player
func (o GetSyntheticNodesNodeOutput) PlayerVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.PlayerVersion }).(pulumi.StringOutput)
}

// The status of the synthetic node
func (o GetSyntheticNodesNodeOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Status }).(pulumi.StringOutput)
}

// The version of a node
func (o GetSyntheticNodesNodeOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetSyntheticNodesNode) string { return v.Version }).(pulumi.StringOutput)
}

type GetSyntheticNodesNodeArrayOutput struct{ *pulumi.OutputState }

func (GetSyntheticNodesNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSyntheticNodesNode)(nil)).Elem()
}

func (o GetSyntheticNodesNodeArrayOutput) ToGetSyntheticNodesNodeArrayOutput() GetSyntheticNodesNodeArrayOutput {
	return o
}

func (o GetSyntheticNodesNodeArrayOutput) ToGetSyntheticNodesNodeArrayOutputWithContext(ctx context.Context) GetSyntheticNodesNodeArrayOutput {
	return o
}

func (o GetSyntheticNodesNodeArrayOutput) Index(i pulumi.IntInput) GetSyntheticNodesNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetSyntheticNodesNode {
		return vs[0].([]GetSyntheticNodesNode)[vs[1].(int)]
	}).(GetSyntheticNodesNodeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetDocumentsValueInput)(nil)).Elem(), GetDocumentsValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDocumentsValueArrayInput)(nil)).Elem(), GetDocumentsValueArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityInput)(nil)).Elem(), GetEntitiesEntityArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityArrayInput)(nil)).Elem(), GetEntitiesEntityArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagInput)(nil)).Elem(), GetEntitiesEntityTagArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagArrayInput)(nil)).Elem(), GetEntitiesEntityTagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagTagInput)(nil)).Elem(), GetEntitiesEntityTagTagArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetEntitiesEntityTagTagArrayInput)(nil)).Elem(), GetEntitiesEntityTagTagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGenericSettingsValueInput)(nil)).Elem(), GetGenericSettingsValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGenericSettingsValueArrayInput)(nil)).Elem(), GetGenericSettingsValueArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGeoCitiesCityInput)(nil)).Elem(), GetGeoCitiesCityArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGeoCitiesCityArrayInput)(nil)).Elem(), GetGeoCitiesCityArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGeoCountriesCountryInput)(nil)).Elem(), GetGeoCountriesCountryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGeoCountriesCountryArrayInput)(nil)).Elem(), GetGeoCountriesCountryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGeoRegionsRegionInput)(nil)).Elem(), GetGeoRegionsRegionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGeoRegionsRegionArrayInput)(nil)).Elem(), GetGeoRegionsRegionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetHubItemsItemInput)(nil)).Elem(), GetHubItemsItemArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetHubItemsItemArrayInput)(nil)).Elem(), GetHubItemsItemArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetIamPoliciesPolicyInput)(nil)).Elem(), GetIamPoliciesPolicyArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetIamPoliciesPolicyArrayInput)(nil)).Elem(), GetIamPoliciesPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetManagementZonesValueInput)(nil)).Elem(), GetManagementZonesValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetManagementZonesValueArrayInput)(nil)).Elem(), GetManagementZonesValueArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPlatformSloTemplatesTemplateInput)(nil)).Elem(), GetPlatformSloTemplatesTemplateArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPlatformSloTemplatesTemplateArrayInput)(nil)).Elem(), GetPlatformSloTemplatesTemplateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironmentInput)(nil)).Elem(), GetRemoteEnvironmentsRemoteEnvironmentArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRemoteEnvironmentsRemoteEnvironmentArrayInput)(nil)).Elem(), GetRemoteEnvironmentsRemoteEnvironmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticLocationsLocationsInput)(nil)).Elem(), GetSyntheticLocationsLocationsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticLocationsLocationsPtrInput)(nil)).Elem(), GetSyntheticLocationsLocationsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticNodesNodeInput)(nil)).Elem(), GetSyntheticNodesNodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSyntheticNodesNodeArrayInput)(nil)).Elem(), GetSyntheticNodesNodeArray{})
	pulumi.RegisterOutputType(GetDocumentsValueOutput{})
	pulumi.RegisterOutputType(GetDocumentsValueArrayOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityArrayOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagArrayOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagTagOutput{})
	pulumi.RegisterOutputType(GetEntitiesEntityTagTagArrayOutput{})
	pulumi.RegisterOutputType(GetGenericSettingsValueOutput{})
	pulumi.RegisterOutputType(GetGenericSettingsValueArrayOutput{})
	pulumi.RegisterOutputType(GetGeoCitiesCityOutput{})
	pulumi.RegisterOutputType(GetGeoCitiesCityArrayOutput{})
	pulumi.RegisterOutputType(GetGeoCountriesCountryOutput{})
	pulumi.RegisterOutputType(GetGeoCountriesCountryArrayOutput{})
	pulumi.RegisterOutputType(GetGeoRegionsRegionOutput{})
	pulumi.RegisterOutputType(GetGeoRegionsRegionArrayOutput{})
	pulumi.RegisterOutputType(GetHubItemsItemOutput{})
	pulumi.RegisterOutputType(GetHubItemsItemArrayOutput{})
	pulumi.RegisterOutputType(GetIamPoliciesPolicyOutput{})
	pulumi.RegisterOutputType(GetIamPoliciesPolicyArrayOutput{})
	pulumi.RegisterOutputType(GetManagementZonesValueOutput{})
	pulumi.RegisterOutputType(GetManagementZonesValueArrayOutput{})
	pulumi.RegisterOutputType(GetPlatformSloTemplatesTemplateOutput{})
	pulumi.RegisterOutputType(GetPlatformSloTemplatesTemplateArrayOutput{})
	pulumi.RegisterOutputType(GetRemoteEnvironmentsRemoteEnvironmentOutput{})
	pulumi.RegisterOutputType(GetRemoteEnvironmentsRemoteEnvironmentArrayOutput{})
	pulumi.RegisterOutputType(GetSyntheticLocationsLocationsOutput{})
	pulumi.RegisterOutputType(GetSyntheticLocationsLocationsPtrOutput{})
	pulumi.RegisterOutputType(GetSyntheticNodesNodeOutput{})
	pulumi.RegisterOutputType(GetSyntheticNodesNodeArrayOutput{})
}
