// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class BrowserMonitorScriptEventsEventCookieCookiesCookieGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public BrowserMonitorScriptEventsEventCookieCookiesCookieGetArgs()
        {
        }
        public static new BrowserMonitorScriptEventsEventCookieCookiesCookieGetArgs Empty => new BrowserMonitorScriptEventsEventCookieCookiesCookieGetArgs();
    }
}
