// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Dynatrace.Inputs
{

    public sealed class BrowserMonitorScriptConfigurationCookiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("cookies", required: true)]
        private InputList<Inputs.BrowserMonitorScriptConfigurationCookiesCookieArgs>? _cookies;
        public InputList<Inputs.BrowserMonitorScriptConfigurationCookiesCookieArgs> Cookies
        {
            get => _cookies ?? (_cookies = new InputList<Inputs.BrowserMonitorScriptConfigurationCookiesCookieArgs>());
            set => _cookies = value;
        }

        public BrowserMonitorScriptConfigurationCookiesArgs()
        {
        }
        public static new BrowserMonitorScriptConfigurationCookiesArgs Empty => new BrowserMonitorScriptConfigurationCookiesArgs();
    }
}
