// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.PulumiPackage.Dynatrace.Inputs
{

    public sealed class OsServicesMetadataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("items", required: true)]
        private InputList<Inputs.OsServicesMetadataItemGetArgs>? _items;
        public InputList<Inputs.OsServicesMetadataItemGetArgs> Items
        {
            get => _items ?? (_items = new InputList<Inputs.OsServicesMetadataItemGetArgs>());
            set => _items = value;
        }

        public OsServicesMetadataGetArgs()
        {
        }
        public static new OsServicesMetadataGetArgs Empty => new OsServicesMetadataGetArgs();
    }
}
