// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.dynatrace.outputs.DiskAnomaliesV2DiskDiskLowInodesDetection;
import com.pulumi.dynatrace.outputs.DiskAnomaliesV2DiskDiskLowSpaceDetection;
import com.pulumi.dynatrace.outputs.DiskAnomaliesV2DiskDiskSlowWritesAndReadsDetection;
import java.util.Objects;

@CustomType
public final class DiskAnomaliesV2Disk {
    /**
     * @return no documentation available
     * 
     */
    private DiskAnomaliesV2DiskDiskLowInodesDetection diskLowInodesDetection;
    /**
     * @return no documentation available
     * 
     */
    private DiskAnomaliesV2DiskDiskLowSpaceDetection diskLowSpaceDetection;
    /**
     * @return no documentation available
     * 
     */
    private DiskAnomaliesV2DiskDiskSlowWritesAndReadsDetection diskSlowWritesAndReadsDetection;

    private DiskAnomaliesV2Disk() {}
    /**
     * @return no documentation available
     * 
     */
    public DiskAnomaliesV2DiskDiskLowInodesDetection diskLowInodesDetection() {
        return this.diskLowInodesDetection;
    }
    /**
     * @return no documentation available
     * 
     */
    public DiskAnomaliesV2DiskDiskLowSpaceDetection diskLowSpaceDetection() {
        return this.diskLowSpaceDetection;
    }
    /**
     * @return no documentation available
     * 
     */
    public DiskAnomaliesV2DiskDiskSlowWritesAndReadsDetection diskSlowWritesAndReadsDetection() {
        return this.diskSlowWritesAndReadsDetection;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DiskAnomaliesV2Disk defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private DiskAnomaliesV2DiskDiskLowInodesDetection diskLowInodesDetection;
        private DiskAnomaliesV2DiskDiskLowSpaceDetection diskLowSpaceDetection;
        private DiskAnomaliesV2DiskDiskSlowWritesAndReadsDetection diskSlowWritesAndReadsDetection;
        public Builder() {}
        public Builder(DiskAnomaliesV2Disk defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.diskLowInodesDetection = defaults.diskLowInodesDetection;
    	      this.diskLowSpaceDetection = defaults.diskLowSpaceDetection;
    	      this.diskSlowWritesAndReadsDetection = defaults.diskSlowWritesAndReadsDetection;
        }

        @CustomType.Setter
        public Builder diskLowInodesDetection(DiskAnomaliesV2DiskDiskLowInodesDetection diskLowInodesDetection) {
            this.diskLowInodesDetection = Objects.requireNonNull(diskLowInodesDetection);
            return this;
        }
        @CustomType.Setter
        public Builder diskLowSpaceDetection(DiskAnomaliesV2DiskDiskLowSpaceDetection diskLowSpaceDetection) {
            this.diskLowSpaceDetection = Objects.requireNonNull(diskLowSpaceDetection);
            return this;
        }
        @CustomType.Setter
        public Builder diskSlowWritesAndReadsDetection(DiskAnomaliesV2DiskDiskSlowWritesAndReadsDetection diskSlowWritesAndReadsDetection) {
            this.diskSlowWritesAndReadsDetection = Objects.requireNonNull(diskSlowWritesAndReadsDetection);
            return this;
        }
        public DiskAnomaliesV2Disk build() {
            final var o = new DiskAnomaliesV2Disk();
            o.diskLowInodesDetection = diskLowInodesDetection;
            o.diskLowSpaceDetection = diskLowSpaceDetection;
            o.diskSlowWritesAndReadsDetection = diskSlowWritesAndReadsDetection;
            return o;
        }
    }
}
