// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.util.Objects;

@CustomType
public final class WebAppAnomaliesTrafficSpikesTrafficSpikes {
    private Double minutesAbnormalState;
    private Double trafficSpikePercentage;

    private WebAppAnomaliesTrafficSpikesTrafficSpikes() {}
    public Double minutesAbnormalState() {
        return this.minutesAbnormalState;
    }
    public Double trafficSpikePercentage() {
        return this.trafficSpikePercentage;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WebAppAnomaliesTrafficSpikesTrafficSpikes defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double minutesAbnormalState;
        private Double trafficSpikePercentage;
        public Builder() {}
        public Builder(WebAppAnomaliesTrafficSpikesTrafficSpikes defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.minutesAbnormalState = defaults.minutesAbnormalState;
    	      this.trafficSpikePercentage = defaults.trafficSpikePercentage;
        }

        @CustomType.Setter
        public Builder minutesAbnormalState(Double minutesAbnormalState) {
            this.minutesAbnormalState = Objects.requireNonNull(minutesAbnormalState);
            return this;
        }
        @CustomType.Setter
        public Builder trafficSpikePercentage(Double trafficSpikePercentage) {
            this.trafficSpikePercentage = Objects.requireNonNull(trafficSpikePercentage);
            return this;
        }
        public WebAppAnomaliesTrafficSpikesTrafficSpikes build() {
            final var o = new WebAppAnomaliesTrafficSpikesTrafficSpikes();
            o.minutesAbnormalState = minutesAbnormalState;
            o.trafficSpikePercentage = trafficSpikePercentage;
            return o;
        }
    }
}
