// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.dynatrace.outputs.WebApplicationUserActionNamingSettingsXhrActionNamingRulesRule;
import java.util.List;
import java.util.Objects;

@CustomType
public final class WebApplicationUserActionNamingSettingsXhrActionNamingRules {
    private List<WebApplicationUserActionNamingSettingsXhrActionNamingRulesRule> rules;

    private WebApplicationUserActionNamingSettingsXhrActionNamingRules() {}
    public List<WebApplicationUserActionNamingSettingsXhrActionNamingRulesRule> rules() {
        return this.rules;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WebApplicationUserActionNamingSettingsXhrActionNamingRules defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<WebApplicationUserActionNamingSettingsXhrActionNamingRulesRule> rules;
        public Builder() {}
        public Builder(WebApplicationUserActionNamingSettingsXhrActionNamingRules defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.rules = defaults.rules;
        }

        @CustomType.Setter
        public Builder rules(List<WebApplicationUserActionNamingSettingsXhrActionNamingRulesRule> rules) {
            this.rules = Objects.requireNonNull(rules);
            return this;
        }
        public Builder rules(WebApplicationUserActionNamingSettingsXhrActionNamingRulesRule... rules) {
            return rules(List.of(rules));
        }
        public WebApplicationUserActionNamingSettingsXhrActionNamingRules build() {
            final var o = new WebApplicationUserActionNamingSettingsXhrActionNamingRules();
            o.rules = rules;
            return o;
        }
    }
}
