// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dynatrace.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsEventWrapperSettings {
    private @Nullable Boolean blur;
    private @Nullable Boolean change;
    private @Nullable Boolean click;
    private @Nullable Boolean mouseup;
    private @Nullable Boolean touchEnd;
    private @Nullable Boolean touchStart;

    private WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsEventWrapperSettings() {}
    public Optional<Boolean> blur() {
        return Optional.ofNullable(this.blur);
    }
    public Optional<Boolean> change() {
        return Optional.ofNullable(this.change);
    }
    public Optional<Boolean> click() {
        return Optional.ofNullable(this.click);
    }
    public Optional<Boolean> mouseup() {
        return Optional.ofNullable(this.mouseup);
    }
    public Optional<Boolean> touchEnd() {
        return Optional.ofNullable(this.touchEnd);
    }
    public Optional<Boolean> touchStart() {
        return Optional.ofNullable(this.touchStart);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsEventWrapperSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean blur;
        private @Nullable Boolean change;
        private @Nullable Boolean click;
        private @Nullable Boolean mouseup;
        private @Nullable Boolean touchEnd;
        private @Nullable Boolean touchStart;
        public Builder() {}
        public Builder(WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsEventWrapperSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.blur = defaults.blur;
    	      this.change = defaults.change;
    	      this.click = defaults.click;
    	      this.mouseup = defaults.mouseup;
    	      this.touchEnd = defaults.touchEnd;
    	      this.touchStart = defaults.touchStart;
        }

        @CustomType.Setter
        public Builder blur(@Nullable Boolean blur) {
            this.blur = blur;
            return this;
        }
        @CustomType.Setter
        public Builder change(@Nullable Boolean change) {
            this.change = change;
            return this;
        }
        @CustomType.Setter
        public Builder click(@Nullable Boolean click) {
            this.click = click;
            return this;
        }
        @CustomType.Setter
        public Builder mouseup(@Nullable Boolean mouseup) {
            this.mouseup = mouseup;
            return this;
        }
        @CustomType.Setter
        public Builder touchEnd(@Nullable Boolean touchEnd) {
            this.touchEnd = touchEnd;
            return this;
        }
        @CustomType.Setter
        public Builder touchStart(@Nullable Boolean touchStart) {
            this.touchStart = touchStart;
            return this;
        }
        public WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsEventWrapperSettings build() {
            final var o = new WebApplicationMonitoringSettingsAdvancedJavascriptTagSettingsEventWrapperSettings();
            o.blur = blur;
            o.change = change;
            o.click = click;
            o.mouseup = mouseup;
            o.touchEnd = touchEnd;
            o.touchStart = touchStart;
            return o;
        }
    }
}
