// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class AutomationWorkflowTriggerEventConfigDavisEventNamesArgs : global::Pulumi.ResourceArgs
    {
        [Input("names")]
        private InputList<Inputs.AutomationWorkflowTriggerEventConfigDavisEventNamesNameArgs>? _names;

        /// <summary>
        /// A combination of name and match
        /// </summary>
        public InputList<Inputs.AutomationWorkflowTriggerEventConfigDavisEventNamesNameArgs> Names
        {
            get => _names ?? (_names = new InputList<Inputs.AutomationWorkflowTriggerEventConfigDavisEventNamesNameArgs>());
            set => _names = value;
        }

        public AutomationWorkflowTriggerEventConfigDavisEventNamesArgs()
        {
        }
        public static new AutomationWorkflowTriggerEventConfigDavisEventNamesArgs Empty => new AutomationWorkflowTriggerEventConfigDavisEventNamesArgs();
    }
}
