// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class AutotagRuleConditionIndexedTagArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Reverses the operator. For example it turns EQUALS into DOES NOT EQUAL
        /// </summary>
        [Input("negate")]
        public Input<bool>? Negate { get; set; }

        /// <summary>
        /// Either EQUALS or EXISTS. You can reverse it by setting **negate** to `True`
        /// </summary>
        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        /// <summary>
        /// Any attributes that aren't yet supported by this provider but have meanwhile gotten introduced by a newer version of the Dynatrace REST API
        /// </summary>
        [Input("unknowns")]
        public Input<string>? Unknowns { get; set; }

        /// <summary>
        /// Tag of a Dynatrace entity
        /// </summary>
        [Input("value")]
        public Input<Inputs.AutotagRuleConditionIndexedTagValueArgs>? Value { get; set; }

        public AutotagRuleConditionIndexedTagArgs()
        {
        }
        public static new AutotagRuleConditionIndexedTagArgs Empty => new AutotagRuleConditionIndexedTagArgs();
    }
}
