// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class BusinessEventsOneagentOutgoingEventDataEventDataFieldComplexGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field name to be added to data.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// no documentation available
        /// </summary>
        [Input("source", required: true)]
        public Input<Inputs.BusinessEventsOneagentOutgoingEventDataEventDataFieldComplexSourceGetArgs> Source { get; set; } = null!;

        public BusinessEventsOneagentOutgoingEventDataEventDataFieldComplexGetArgs()
        {
        }
        public static new BusinessEventsOneagentOutgoingEventDataEventDataFieldComplexGetArgs Empty => new BusinessEventsOneagentOutgoingEventDataEventDataFieldComplexGetArgs();
    }
}
