// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class NetworkMonitorPerformanceThresholdsThresholdsArgs : global::Pulumi.ResourceArgs
    {
        [Input("thresholds")]
        private InputList<Inputs.NetworkMonitorPerformanceThresholdsThresholdsThresholdArgs>? _thresholds;

        /// <summary>
        /// The list of performance threshold rules
        /// </summary>
        public InputList<Inputs.NetworkMonitorPerformanceThresholdsThresholdsThresholdArgs> Thresholds
        {
            get => _thresholds ?? (_thresholds = new InputList<Inputs.NetworkMonitorPerformanceThresholdsThresholdsThresholdArgs>());
            set => _thresholds = value;
        }

        public NetworkMonitorPerformanceThresholdsThresholdsArgs()
        {
        }
        public static new NetworkMonitorPerformanceThresholdsThresholdsArgs Empty => new NetworkMonitorPerformanceThresholdsThresholdsArgs();
    }
}
