// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2LogsPipelinesCostAllocationProcessorsProcessorProductAllocationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The strategy to set product allocation field
        /// </summary>
        [Input("value", required: true)]
        public Input<Inputs.OpenpipelineV2LogsPipelinesCostAllocationProcessorsProcessorProductAllocationValueArgs> Value { get; set; } = null!;

        public OpenpipelineV2LogsPipelinesCostAllocationProcessorsProcessorProductAllocationArgs()
        {
        }
        public static new OpenpipelineV2LogsPipelinesCostAllocationProcessorsProcessorProductAllocationArgs Empty => new OpenpipelineV2LogsPipelinesCostAllocationProcessorsProcessorProductAllocationArgs();
    }
}
