// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractArgs : global::Pulumi.ResourceArgs
    {
        [Input("smartscapeFieldExtractionEntries", required: true)]
        private InputList<Inputs.OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractSmartscapeFieldExtractionEntryArgs>? _smartscapeFieldExtractionEntries;
        public InputList<Inputs.OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractSmartscapeFieldExtractionEntryArgs> SmartscapeFieldExtractionEntries
        {
            get => _smartscapeFieldExtractionEntries ?? (_smartscapeFieldExtractionEntries = new InputList<Inputs.OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractSmartscapeFieldExtractionEntryArgs>());
            set => _smartscapeFieldExtractionEntries = value;
        }

        public OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractArgs()
        {
        }
        public static new OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractArgs Empty => new OpenpipelineV2SecurityEventsPipelinesProcessingProcessorsProcessorSmartscapeNodeFieldsToExtractArgs();
    }
}
