// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2UserEventsRoutingRoutingEntriesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("routingEntries", required: true)]
        private InputList<Inputs.OpenpipelineV2UserEventsRoutingRoutingEntriesRoutingEntryGetArgs>? _routingEntries;
        public InputList<Inputs.OpenpipelineV2UserEventsRoutingRoutingEntriesRoutingEntryGetArgs> RoutingEntries
        {
            get => _routingEntries ?? (_routingEntries = new InputList<Inputs.OpenpipelineV2UserEventsRoutingRoutingEntriesRoutingEntryGetArgs>());
            set => _routingEntries = value;
        }

        public OpenpipelineV2UserEventsRoutingRoutingEntriesGetArgs()
        {
        }
        public static new OpenpipelineV2UserEventsRoutingRoutingEntriesGetArgs Empty => new OpenpipelineV2UserEventsRoutingRoutingEntriesGetArgs();
    }
}
