// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2SecurityEventsPipelinesCostAllocationProcessorsProcessorFieldsAddArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fields to Add
        /// </summary>
        [Input("fields", required: true)]
        public Input<Inputs.OpenpipelineV2SecurityEventsPipelinesCostAllocationProcessorsProcessorFieldsAddFieldsArgs> Fields { get; set; } = null!;

        public OpenpipelineV2SecurityEventsPipelinesCostAllocationProcessorsProcessorFieldsAddArgs()
        {
        }
        public static new OpenpipelineV2SecurityEventsPipelinesCostAllocationProcessorsProcessorFieldsAddArgs Empty => new OpenpipelineV2SecurityEventsPipelinesCostAllocationProcessorsProcessorFieldsAddArgs();
    }
}
