// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2UserEventsPipelinesDavisProcessorsProcessorCostAllocationValueFieldArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Default value
        /// </summary>
        [Input("defaultValue")]
        public Input<string>? DefaultValue { get; set; }

        /// <summary>
        /// Source field name
        /// </summary>
        [Input("sourceFieldName", required: true)]
        public Input<string> SourceFieldName { get; set; } = null!;

        public OpenpipelineV2UserEventsPipelinesDavisProcessorsProcessorCostAllocationValueFieldArgs()
        {
        }
        public static new OpenpipelineV2UserEventsPipelinesDavisProcessorsProcessorCostAllocationValueFieldArgs Empty => new OpenpipelineV2UserEventsPipelinesDavisProcessorsProcessorCostAllocationValueFieldArgs();
    }
}
