// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsArgs : global::Pulumi.ResourceArgs
    {
        [Input("fields", required: true)]
        private InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsFieldArgs>? _fields;
        public InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsFieldArgs> Fields
        {
            get => _fields ?? (_fields = new InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsFieldArgs>());
            set => _fields = value;
        }

        public OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsArgs()
        {
        }
        public static new OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsArgs Empty => new OpenpipelineV2DavisProblemsPipelinesSecurityContextProcessorsProcessorFieldsAddFieldsArgs();
    }
}
