// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2SystemEventsPipelinesProductAllocationProcessorsProcessorCounterMetricArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// List of dimensions
        /// </summary>
        [Input("dimensions")]
        public Input<Inputs.OpenpipelineV2SystemEventsPipelinesProductAllocationProcessorsProcessorCounterMetricDimensionsArgs>? Dimensions { get; set; }

        /// <summary>
        /// Metric key
        /// </summary>
        [Input("metricKey", required: true)]
        public Input<string> MetricKey { get; set; } = null!;

        public OpenpipelineV2SystemEventsPipelinesProductAllocationProcessorsProcessorCounterMetricArgs()
        {
        }
        public static new OpenpipelineV2SystemEventsPipelinesProductAllocationProcessorsProcessorCounterMetricArgs Empty => new OpenpipelineV2SystemEventsPipelinesProductAllocationProcessorsProcessorCounterMetricArgs();
    }
}
