// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeArgs : global::Pulumi.ResourceArgs
    {
        [Input("dimensions", required: true)]
        private InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeDimensionArgs>? _dimensions;
        public InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeDimensionArgs> Dimensions
        {
            get => _dimensions ?? (_dimensions = new InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeDimensionArgs>());
            set => _dimensions = value;
        }

        public OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeArgs()
        {
        }
        public static new OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeArgs Empty => new OpenpipelineV2DavisProblemsPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeArgs();
    }
}
