// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeArgs : global::Pulumi.ResourceArgs
    {
        [Input("dimensions", required: true)]
        private InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeDimensionArgs>? _dimensions;
        public InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeDimensionArgs> Dimensions
        {
            get => _dimensions ?? (_dimensions = new InputList<Inputs.OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeDimensionArgs>());
            set => _dimensions = value;
        }

        public OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeArgs()
        {
        }
        public static new OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeArgs Empty => new OpenpipelineV2DavisProblemsPipelinesProductAllocationProcessorsProcessorSdlcEventFieldExtractionIncludeArgs();
    }
}
