// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2EventsSecurityPipelinesDavisProcessorsProcessorSecurityContextGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Security context value assignment
        /// </summary>
        [Input("value", required: true)]
        public Input<Inputs.OpenpipelineV2EventsSecurityPipelinesDavisProcessorsProcessorSecurityContextValueGetArgs> Value { get; set; } = null!;

        public OpenpipelineV2EventsSecurityPipelinesDavisProcessorsProcessorSecurityContextGetArgs()
        {
        }
        public static new OpenpipelineV2EventsSecurityPipelinesDavisProcessorsProcessorSecurityContextGetArgs Empty => new OpenpipelineV2EventsSecurityPipelinesDavisProcessorsProcessorSecurityContextGetArgs();
    }
}
