// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("dimensions", required: true)]
        private InputList<Inputs.OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeDimensionGetArgs>? _dimensions;
        public InputList<Inputs.OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeDimensionGetArgs> Dimensions
        {
            get => _dimensions ?? (_dimensions = new InputList<Inputs.OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeDimensionGetArgs>());
            set => _dimensions = value;
        }

        public OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeGetArgs()
        {
        }
        public static new OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeGetArgs Empty => new OpenpipelineV2EventsSecurityPipelinesCostAllocationProcessorsProcessorAzureLogForwardingFieldExtractionIncludeGetArgs();
    }
}
