// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractArgs : global::Pulumi.ResourceArgs
    {
        [Input("smartscapeStaticEdgeExtractionEntries", required: true)]
        private InputList<Inputs.OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractSmartscapeStaticEdgeExtractionEntryArgs>? _smartscapeStaticEdgeExtractionEntries;
        public InputList<Inputs.OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractSmartscapeStaticEdgeExtractionEntryArgs> SmartscapeStaticEdgeExtractionEntries
        {
            get => _smartscapeStaticEdgeExtractionEntries ?? (_smartscapeStaticEdgeExtractionEntries = new InputList<Inputs.OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractSmartscapeStaticEdgeExtractionEntryArgs>());
            set => _smartscapeStaticEdgeExtractionEntries = value;
        }

        public OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractArgs()
        {
        }
        public static new OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractArgs Empty => new OpenpipelineV2MetricsPipelinesCostAllocationProcessorsProcessorSmartscapeNodeStaticEdgesToExtractArgs();
    }
}
