// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2SecurityEventsPipelinesDataExtractionProcessorsProcessorDavisArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// no documentation available
        /// </summary>
        [Input("properties", required: true)]
        public Input<Inputs.OpenpipelineV2SecurityEventsPipelinesDataExtractionProcessorsProcessorDavisPropertiesArgs> Properties { get; set; } = null!;

        public OpenpipelineV2SecurityEventsPipelinesDataExtractionProcessorsProcessorDavisArgs()
        {
        }
        public static new OpenpipelineV2SecurityEventsPipelinesDataExtractionProcessorsProcessorDavisArgs Empty => new OpenpipelineV2SecurityEventsPipelinesDataExtractionProcessorsProcessorDavisArgs();
    }
}
