// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2BizeventsPipelinesStorageProcessorsProcessorSecurityEventArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field Extraction
        /// </summary>
        [Input("fieldExtraction", required: true)]
        public Input<Inputs.OpenpipelineV2BizeventsPipelinesStorageProcessorsProcessorSecurityEventFieldExtractionArgs> FieldExtraction { get; set; } = null!;

        public OpenpipelineV2BizeventsPipelinesStorageProcessorsProcessorSecurityEventArgs()
        {
        }
        public static new OpenpipelineV2BizeventsPipelinesStorageProcessorsProcessorSecurityEventArgs Empty => new OpenpipelineV2BizeventsPipelinesStorageProcessorsProcessorSecurityEventArgs();
    }
}
