// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2EventsPipelinesSecurityContextProcessorsProcessorCostAllocationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The strategy to set the cost allocation field
        /// </summary>
        [Input("value", required: true)]
        public Input<Inputs.OpenpipelineV2EventsPipelinesSecurityContextProcessorsProcessorCostAllocationValueArgs> Value { get; set; } = null!;

        public OpenpipelineV2EventsPipelinesSecurityContextProcessorsProcessorCostAllocationArgs()
        {
        }
        public static new OpenpipelineV2EventsPipelinesSecurityContextProcessorsProcessorCostAllocationArgs Empty => new OpenpipelineV2EventsPipelinesSecurityContextProcessorsProcessorCostAllocationArgs();
    }
}
