// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2SpansPipelinesSecurityContextProcessorsProcessorTechnologyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Custom matching condition which should be used instead of technology matcher.
        /// </summary>
        [Input("customMatcher")]
        public Input<string>? CustomMatcher { get; set; }

        /// <summary>
        /// Technology ID
        /// </summary>
        [Input("technologyId", required: true)]
        public Input<string> TechnologyId { get; set; } = null!;

        public OpenpipelineV2SpansPipelinesSecurityContextProcessorsProcessorTechnologyArgs()
        {
        }
        public static new OpenpipelineV2SpansPipelinesSecurityContextProcessorsProcessorTechnologyArgs Empty => new OpenpipelineV2SpansPipelinesSecurityContextProcessorsProcessorTechnologyArgs();
    }
}
