// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class OpenpipelineV2EventsIngestsourcesProcessingProcessorsProcessorDqlArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// DQL script
        /// </summary>
        [Input("script", required: true)]
        public Input<string> Script { get; set; } = null!;

        public OpenpipelineV2EventsIngestsourcesProcessingProcessorsProcessorDqlArgs()
        {
        }
        public static new OpenpipelineV2EventsIngestsourcesProcessingProcessorsProcessorDqlArgs Empty => new OpenpipelineV2EventsIngestsourcesProcessingProcessorsProcessorDqlArgs();
    }
}
