// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class PlatformSloCustomSliFilterSegmentsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("filterSegments", required: true)]
        private InputList<Inputs.PlatformSloCustomSliFilterSegmentsFilterSegmentGetArgs>? _filterSegments;
        public InputList<Inputs.PlatformSloCustomSliFilterSegmentsFilterSegmentGetArgs> FilterSegments
        {
            get => _filterSegments ?? (_filterSegments = new InputList<Inputs.PlatformSloCustomSliFilterSegmentsFilterSegmentGetArgs>());
            set => _filterSegments = value;
        }

        public PlatformSloCustomSliFilterSegmentsGetArgs()
        {
        }
        public static new PlatformSloCustomSliFilterSegmentsGetArgs Empty => new PlatformSloCustomSliFilterSegmentsGetArgs();
    }
}
