// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class ServiceSplittingRuleServiceSplittingAttributesArgs : global::Pulumi.ResourceArgs
    {
        [Input("serviceSplittingAttributes", required: true)]
        private InputList<Inputs.ServiceSplittingRuleServiceSplittingAttributesServiceSplittingAttributeArgs>? _serviceSplittingAttributes;
        public InputList<Inputs.ServiceSplittingRuleServiceSplittingAttributesServiceSplittingAttributeArgs> ServiceSplittingAttributes
        {
            get => _serviceSplittingAttributes ?? (_serviceSplittingAttributes = new InputList<Inputs.ServiceSplittingRuleServiceSplittingAttributesServiceSplittingAttributeArgs>());
            set => _serviceSplittingAttributes = value;
        }

        public ServiceSplittingRuleServiceSplittingAttributesArgs()
        {
        }
        public static new ServiceSplittingRuleServiceSplittingAttributesArgs Empty => new ServiceSplittingRuleServiceSplittingAttributesArgs();
    }
}
