// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class SettingsPermissionsUsersArgs : global::Pulumi.ResourceArgs
    {
        [Input("users", required: true)]
        private InputList<Inputs.SettingsPermissionsUsersUserArgs>? _users;

        /// <summary>
        /// User that is to be granted read or write permissions
        /// </summary>
        public InputList<Inputs.SettingsPermissionsUsersUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.SettingsPermissionsUsersUserArgs>());
            set => _users = value;
        }

        public SettingsPermissionsUsersArgs()
        {
        }
        public static new SettingsPermissionsUsersArgs Empty => new SettingsPermissionsUsersArgs();
    }
}
