// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class SiteReliabilityGuardianObjectivesObjectiveLinksLinkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Short description for the link.
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        /// <summary>
        /// HTTPS link associated with this objective.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public SiteReliabilityGuardianObjectivesObjectiveLinksLinkArgs()
        {
        }
        public static new SiteReliabilityGuardianObjectivesObjectiveLinksLinkArgs Empty => new SiteReliabilityGuardianObjectivesObjectiveLinksLinkArgs();
    }
}
