// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Dynatrace.Inputs
{

    public sealed class WebAppManualInsertionOneagentJavascriptTagArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Possible Values: `Async`, `Defer`, `None`
        /// </summary>
        [Input("scriptExecutionAttribute")]
        public Input<string>? ScriptExecutionAttribute { get; set; }

        public WebAppManualInsertionOneagentJavascriptTagArgs()
        {
        }
        public static new WebAppManualInsertionOneagentJavascriptTagArgs Empty => new WebAppManualInsertionOneagentJavascriptTagArgs();
    }
}
