// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ActivegateUpdates extends pulumi.CustomResource {
    /**
     * Get an existing ActivegateUpdates resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ActivegateUpdatesState, opts?: pulumi.CustomResourceOptions): ActivegateUpdates {
        return new ActivegateUpdates(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dynatrace:index/activegateUpdates:ActivegateUpdates';

    /**
     * Returns true if the given object is an instance of ActivegateUpdates.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ActivegateUpdates {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ActivegateUpdates.__pulumiType;
    }

    /**
     * Automatic updates at earliest convenience
     */
    public readonly autoUpdate!: pulumi.Output<boolean>;
    /**
     * The scope of this setting (ENVIRONMENT*ACTIVE*GATE). Omit this property if you want to cover the whole environment.
     */
    public readonly scope!: pulumi.Output<string | undefined>;

    /**
     * Create a ActivegateUpdates resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ActivegateUpdatesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ActivegateUpdatesArgs | ActivegateUpdatesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ActivegateUpdatesState | undefined;
            resourceInputs["autoUpdate"] = state ? state.autoUpdate : undefined;
            resourceInputs["scope"] = state ? state.scope : undefined;
        } else {
            const args = argsOrState as ActivegateUpdatesArgs | undefined;
            if ((!args || args.autoUpdate === undefined) && !opts.urn) {
                throw new Error("Missing required property 'autoUpdate'");
            }
            resourceInputs["autoUpdate"] = args ? args.autoUpdate : undefined;
            resourceInputs["scope"] = args ? args.scope : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ActivegateUpdates.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ActivegateUpdates resources.
 */
export interface ActivegateUpdatesState {
    /**
     * Automatic updates at earliest convenience
     */
    autoUpdate?: pulumi.Input<boolean>;
    /**
     * The scope of this setting (ENVIRONMENT*ACTIVE*GATE). Omit this property if you want to cover the whole environment.
     */
    scope?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ActivegateUpdates resource.
 */
export interface ActivegateUpdatesArgs {
    /**
     * Automatic updates at earliest convenience
     */
    autoUpdate: pulumi.Input<boolean>;
    /**
     * The scope of this setting (ENVIRONMENT*ACTIVE*GATE). Omit this property if you want to cover the whole environment.
     */
    scope?: pulumi.Input<string>;
}
