// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RemoteEnvironments extends pulumi.CustomResource {
    /**
     * Get an existing RemoteEnvironments resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RemoteEnvironmentsState, opts?: pulumi.CustomResourceOptions): RemoteEnvironments {
        return new RemoteEnvironments(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dynatrace:index/remoteEnvironments:RemoteEnvironments';

    /**
     * Returns true if the given object is an instance of RemoteEnvironments.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RemoteEnvironments {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RemoteEnvironments.__pulumiType;
    }

    /**
     * Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Possible Values: `CLUSTER`, `EXTERNAL`, `INTERNAL`
     */
    declare public readonly networkScope: pulumi.Output<string>;
    /**
     * Provide a valid token created on the remote environment.
     */
    declare public readonly token: pulumi.Output<string>;
    /**
     * Specify the full URI to the remote environment. Your local environment will have to be able to connect this URI on a network level.
     */
    declare public readonly uri: pulumi.Output<string>;

    /**
     * Create a RemoteEnvironments resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RemoteEnvironmentsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RemoteEnvironmentsArgs | RemoteEnvironmentsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RemoteEnvironmentsState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkScope"] = state?.networkScope;
            resourceInputs["token"] = state?.token;
            resourceInputs["uri"] = state?.uri;
        } else {
            const args = argsOrState as RemoteEnvironmentsArgs | undefined;
            if (args?.networkScope === undefined && !opts.urn) {
                throw new Error("Missing required property 'networkScope'");
            }
            if (args?.token === undefined && !opts.urn) {
                throw new Error("Missing required property 'token'");
            }
            if (args?.uri === undefined && !opts.urn) {
                throw new Error("Missing required property 'uri'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["networkScope"] = args?.networkScope;
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
            resourceInputs["uri"] = args?.uri;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RemoteEnvironments.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RemoteEnvironments resources.
 */
export interface RemoteEnvironmentsState {
    /**
     * Name
     */
    name?: pulumi.Input<string>;
    /**
     * Possible Values: `CLUSTER`, `EXTERNAL`, `INTERNAL`
     */
    networkScope?: pulumi.Input<string>;
    /**
     * Provide a valid token created on the remote environment.
     */
    token?: pulumi.Input<string>;
    /**
     * Specify the full URI to the remote environment. Your local environment will have to be able to connect this URI on a network level.
     */
    uri?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RemoteEnvironments resource.
 */
export interface RemoteEnvironmentsArgs {
    /**
     * Name
     */
    name?: pulumi.Input<string>;
    /**
     * Possible Values: `CLUSTER`, `EXTERNAL`, `INTERNAL`
     */
    networkScope: pulumi.Input<string>;
    /**
     * Provide a valid token created on the remote environment.
     */
    token: pulumi.Input<string>;
    /**
     * Specify the full URI to the remote environment. Your local environment will have to be able to connect this URI on a network level.
     */
    uri: pulumi.Input<string>;
}
